@file:androidx.annotation.OptIn(androidx.media3.common.util.UnstableApi::class)
package com.hhst.youtubelite.extractor

import android.media.MediaExtractor
import android.media.MediaFormat
import android.os.Bundle
import androidx.test.ext.junit.rules.ActivityScenarioRule
import androidx.test.platform.app.InstrumentationRegistry
import com.google.gson.Gson
import com.hhst.youtubelite.downloader.core.*
import com.hhst.youtubelite.downloader.io.FileIntegrity
import com.hhst.youtubelite.downloader.mux.DownloadFinalizerImpl
import com.hhst.youtubelite.downloader.net.DownloadTransportImpl
import com.hhst.youtubelite.downloader.net.YoutubeDownloadRequestAdapter
import com.hhst.youtubelite.downloader.resolve.*
import com.hhst.youtubelite.downloader.ui.DownloadPresentation
import com.hhst.youtubelite.player.datasource.SubtitleSelection
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.runBlocking
import okhttp3.OkHttpClient
import org.junit.Assert.*
import org.junit.Rule
import org.junit.Test
import org.koin.core.context.GlobalContext
import java.io.File
import java.nio.ByteBuffer
import java.util.concurrent.TimeUnit

class YoutubeDownloadSelectionAndroidTest {
    @get:Rule val activity = ActivityScenarioRule(ExtractionTestActivity::class.java)
    @Test fun playbackThenCatalogSelectTransferResumeMuxAndSeek() = runBlocking(Dispatchers.IO) {
        val instrumentation = InstrumentationRegistry.getInstrumentation()
        val app = instrumentation.targetContext
        val id = InstrumentationRegistry.getArguments().getString("videoId") ?: "jNQXAC9IVRw"
        val extractor = GlobalContext.get().get<Extractor>()
        extractor.extract(id).stream.await() // Opening downloads after a playback-only cache hit.
        val catalog = GlobalContext.get().get<DownloadCatalogSource>().catalog(id)
        val qualities = DownloadPresentation.qualityOptions(catalog)
        assertTrue("Download catalog has no enabled quality", qualities.isNotEmpty())
        val requestedQuality = InstrumentationRegistry.getArguments().getString("quality")
        val label = requestedQuality?.also { assertTrue("Requested quality unavailable", it in qualities) }
            ?: qualities.firstOrNull { it == "360p" } ?: qualities.last()
        val subtitle = catalog.subtitles.firstOrNull()
        val config = DownloadConfig(videoQuality = label,
            videoItagHint = DownloadPresentation.qualityItag(catalog, label),
            includeSubtitle = subtitle != null,
            subtitleLanguage = subtitle?.let { SubtitleSelection.key(it.languageCode, it.autoGenerated) })
        val selected = DownloadSelector.select(catalog, config)
        assertTrue("Download selection failed", selected is DownloadSelection.Ready)
        val plan = (selected as DownloadSelection.Ready).plan
        val policy = GlobalContext.get().get<YoutubeMediaRequests>()
        val client = OkHttpClient.Builder().followRedirects(false).followSslRedirects(false)
            .callTimeout(30, TimeUnit.SECONDS).addInterceptor(policy.interceptor()).build()
        val transport = DownloadTransportImpl(client, wifiOnly = false, chunkBytes = 64 * 1024L, mediaRequests = policy)
        val dir = File(app.cacheDir, "followup-download").apply { mkdirs() }
        val record = linkedMapOf<String, Any>("videoId" to id, "qualities" to qualities, "selectedQuality" to label,
            "subtitleAvailable" to (subtitle != null))
        try {
            val choices = listOfNotNull(plan.video, plan.audio, plan.muxed)
            val files = choices.mapIndexed { index, choice ->
                val format = choice.format
                val requestPlan = requireNotNull(format.requestPlan)
                val length = choice.expectedBytes ?: client.newCall(policy.build(format.url, requestPlan, 0, 1))
                    .execute().use { response -> assertEquals(206, response.code); requireNotNull(policy.window(response, requestPlan).total) }
                assertTrue("Acceptance input too large", length in 1..(16L * 1024 * 1024))
                val kind = if (format.audioOnly) InputComponentKind.AUDIO else InputComponentKind.VIDEO
                val component = InputComponent("input-$index", "asset", kind, expectedBytes = length, resourceIdentity = choice.resourceIdentity)
                val request = YoutubeDownloadRequestAdapter.adapt(id, format)
                val source = DownloadComponentSource(AssetKind.VIDEO, kind, format.url, resourceIdentity = choice.resourceIdentity,
                    expectedBytes = length, mimeType = format.mimeType, requestPlan = requestPlan,
                    rangeModeName = request.rangeMode.name, methodName = request.method.name,
                    cookiePolicyName = request.cookiePolicy.name, client = request.client,
                    headers = request.headers, postPulse = request.postPulse)
                val dest = File(dir, "input-$index.mp4")
                val chunks = mutableListOf<DownloadChunk>()
                if (index == 0 && length > 65_536) {
                    assertEquals(TransferResult.Paused, transport.downloadComponent("followup", component, source, dest, emptyList()) {
                        chunks += it; false
                    })
                    assertEquals(1, chunks.size)
                    assertTrue(FileIntegrity.verify(dest, chunks[0].startByte, chunks[0].receivedBytes, chunks[0].checksum))
                    record["pauseResumeVerified"] = true
                }
                assertEquals(TransferResult.Completed, transport.downloadComponent("followup", component, source, dest, chunks.toList()) {
                    chunks += it; true
                })
                assertEquals(length, dest.length())
                record["inputHeader-$index"] = dest.inputStream().use { input ->
                    ByteArray(32).also { input.read(it) }.joinToString("") { "%02x".format(it) }
                }
                dest
            }
            val output = File(dir, "output.mp4")
            val mux = DownloadFinalizerImpl().muxAndVerify(files, output, false)
            record["muxResult"] = mux.toString()
            record["inputFormats"] = choices.map { "${it.format.itag}:${it.format.mimeType}:${it.expectedBytes}" }
            assertTrue("Mux failed: $mux", mux is MuxResult.Ok)
            val reader = MediaExtractor()
            try {
                reader.setDataSource(output.path)
                val tracks = (0 until reader.trackCount).map(reader::getTrackFormat)
                val video = tracks.first { it.getString(MediaFormat.KEY_MIME) == "video/avc" }
                assertEquals((plan.video ?: plan.muxed)!!.format.height, video.getInteger(MediaFormat.KEY_HEIGHT))
                assertTrue(tracks.any { it.getString(MediaFormat.KEY_MIME) == "audio/mp4a-latm" })
                val videoIndex = (0 until reader.trackCount).first { reader.getTrackFormat(it).getString(MediaFormat.KEY_MIME) == "video/avc" }
                reader.selectTrack(videoIndex)
                reader.seekTo(1_000_000, MediaExtractor.SEEK_TO_CLOSEST_SYNC)
                assertTrue(reader.readSampleData(ByteBuffer.allocate(2 * 1024 * 1024), 0) > 0)
                record["height"] = video.getInteger(MediaFormat.KEY_HEIGHT)
                record["seekReadable"] = true
                record["muxBytes"] = output.length()
            } finally { reader.release() }
            // Verify the produced samples reach the device decoder, including a real seek.
            val firstFrame = java.util.concurrent.CountDownLatch(1)
            val frames = java.util.concurrent.atomic.AtomicInteger()
            val playbackError = java.util.concurrent.atomic.AtomicReference<String>()
            lateinit var player: androidx.media3.exoplayer.ExoPlayer
            activity.scenario.onActivity { host ->
                player = androidx.media3.exoplayer.ExoPlayer.Builder(host).build().apply {
                    volume = 0f
                    setVideoSurfaceView(host.surface)
                    addListener(object : androidx.media3.common.Player.Listener {
                        override fun onRenderedFirstFrame() { frames.incrementAndGet(); firstFrame.countDown() }
                        override fun onPlayerError(error: androidx.media3.common.PlaybackException) {
                            playbackError.set(error.errorCodeName); firstFrame.countDown()
                        }
                    })
                    setMediaItem(androidx.media3.common.MediaItem.fromUri(output.toURI().toString()))
                    prepare(); play()
                }
            }
            try {
                assertTrue("Downloaded video did not render", firstFrame.await(15, TimeUnit.SECONDS))
                assertNull(playbackError.get())
                assertTrue(frames.get() > 0)
                instrumentation.runOnMainSync { player.seekTo(8_000) }
                val until = android.os.SystemClock.elapsedRealtime() + 8_000
                while (frames.get() < 2 && playbackError.get() == null && android.os.SystemClock.elapsedRealtime() < until) Thread.sleep(100)
                assertNull(playbackError.get())
                assertTrue("Downloaded video seek did not render", frames.get() >= 2)
                record["downloadedFileDecodedAndSeeked"] = true
            } finally { instrumentation.runOnMainSync { player.release() } }
            plan.subtitle?.let { sidecar ->
                client.newCall(policy.build(sidecar.url, requireNotNull(sidecar.requestPlan))).execute().use { response ->
                    assertEquals(200, response.code)
                    val text = requireNotNull(response.body).string()
                    assertTrue("Caption file empty", text.contains("WEBVTT"))
                    record["subtitleLanguage"] = sidecar.language.orEmpty()
                    record["subtitleDownloaded"] = true
                }
            }
            record["audioTrack"] = plan.audio?.audioTrackKey.orEmpty()
            instrumentation.sendStatus(2, Bundle().apply { putString("downloadSelection", Gson().toJson(record)) })
        } finally {
            File(app.filesDir, "followup-download.json").writeText(Gson().toJson(record))
            transport.cancelInFlight("followup")
            dir.listFiles()?.forEach { it.delete() }
            dir.delete()
            client.dispatcher.executorService.shutdown()
        }
    }
}
