package com.hhst.youtubelite.player.datasource

import com.hhst.youtubelite.extractor.Subtitle

/**
 * Caption pick by concrete track identity (`en|manual` / `en|auto`). A
 * language-only preferred value is the pre-identity pref: human captions
 * for that language, then auto-generated.
 */
object SubtitleSelection {

    private const val AUTO = "auto"
    private const val MANUAL = "manual"

    fun key(language: String, autoGenerated: Boolean): String =
        "$language|${if (autoGenerated) AUTO else MANUAL}"

    fun languageOf(trackKey: String): String = trackKey.substringBefore('|')

    fun autoGenerated(trackKey: String): Boolean? {
        val sep = trackKey.indexOf('|')
        if (sep < 0) return null
        return trackKey.substring(sep + 1) == AUTO
    }

    fun select(subtitles: List<Subtitle>, trackKey: String?): List<Subtitle> {
        if (trackKey.isNullOrBlank()) return emptyList()
        val language = languageOf(trackKey)
        val wantAuto = autoGenerated(trackKey)
        val matches = subtitles.filter { it.languageCode.equals(language, ignoreCase = true) }
        if (matches.isEmpty()) return emptyList()
        if (wantAuto != null) {
            return matches.filter { it.autoGenerated == wantAuto }.ifEmpty { matches }.take(1)
        }
        val human = matches.filter { !it.autoGenerated }
        return human.ifEmpty { matches }.take(1)
    }

    /** Maps a stored pref (legacy language or track key) onto a persistable key. */
    fun migrate(preferred: String?, subtitles: List<Subtitle>): String? {
        if (preferred.isNullOrBlank()) return null
        val picked = select(subtitles, preferred).firstOrNull() ?: return preferred
        return key(picked.languageCode, picked.autoGenerated)
    }
}
