package com.hhst.youtubelite.extractor

/** Caption track from the player response. */
data class Subtitle(
    val url: String = "",
    val languageCode: String = "",
    val autoGenerated: Boolean = false,
)

/** Progressive or adaptive media URL. */
data class Format(
    val url: String = "",
    val height: Int = 0,
    val width: Int = 0,
    val bitrate: Int = 0,
    val fps: Int = 0,
    val qualityLabel: String? = null,
    val codec: String? = null,
    val format: String? = null,
    val itag: Int? = null,
    val videoOnly: Boolean = false,
    val audioOnly: Boolean = false,
)

/** Chapter marker from Innertube `/next`. */
data class Chapter(
    val title: String = "",
    val startSeconds: Int = 0,
)

/**
 * Stable video fields from [Extraction.metadata].
 *
 * Count fields use `-1` when omitted (NewPipe convention).
 */
class Metadata {
    var id: String = ""
    var title: String = ""
    var author: String? = null
    var description: String? = null
    /** Length in seconds. */
    var duration: Long = 0L
    var thumbnailUrl: String? = null
    var likeCount: Long = -1L
    var dislikeCount: Long = -1L
    /** Upload time as epoch milliseconds, or null if unknown. */
    var uploadedAt: Long? = null
    var uploaderUrl: String? = null
    var uploaderAvatarUrl: String? = null
    var viewCount: Long = -1L

    fun copyFrom(other: Metadata) {
        id = other.id
        title = other.title
        author = other.author
        description = other.description
        duration = other.duration
        thumbnailUrl = other.thumbnailUrl
        likeCount = other.likeCount
        dislikeCount = other.dislikeCount
        uploadedAt = other.uploadedAt
        uploaderUrl = other.uploaderUrl
        uploaderAvatarUrl = other.uploaderAvatarUrl
        viewCount = other.viewCount
    }
}

/** Formats, captions, and optional DASH/HLS URLs from [Extraction.stream]. */
class Stream {
    var formats: List<Format> = emptyList()
    var subtitles: List<Subtitle> = emptyList()
    var dashUrl: String? = null
    var hlsUrl: String? = null

    fun copyFrom(other: Stream) {
        formats = other.formats
        subtitles = other.subtitles
        dashUrl = other.dashUrl
        hlsUrl = other.hlsUrl
    }
}

/** Chapter list from [Extraction.segment]. */
class Segment {
    var chapters: List<Chapter> = emptyList()

    fun copyFrom(other: Segment) {
        chapters = other.chapters
    }
}

/**
 * Result of [Extractor.extract]: three independent promises for one video.
 *
 * Call [Promise.get] only on the branches you need.
 */
class Extraction(
    val videoId: String,
    val metadata: Promise<Metadata>,
    val stream: Promise<Stream>,
    val segment: Promise<Segment>,
)
