package com.hhst.youtubelite.extractor

import com.google.gson.annotations.SerializedName
import org.schabi.newpipe.extractor.services.youtube.streams.ClientProfile
import org.schabi.newpipe.extractor.services.youtube.streams.FormatKey
import org.schabi.newpipe.extractor.services.youtube.streams.RequestPlan

/** Caption track from the player response. */
data class Subtitle(
    val url: String = "",
    val languageCode: String = "",
    val autoGenerated: Boolean = false,
    val mimeType: String = "",
    @Transient val requestPlan: RequestPlan? = null,
)

/** Progressive or adaptive media URL. */
data class Format(
    val url: String = "",
    val height: Int = 0,
    val width: Int = 0,
    val bitrate: Int = 0,
    val fps: Int = 0,
    val qualityLabel: String? = null,
    val codec: String? = null,
    /** NewPipe MediaFormat.name: the container ("WEBM", "MPEG_4"), not the MIME. */
    @SerializedName("format")
    val container: String? = null,
    val itag: Int? = null,
    val videoOnly: Boolean = false,
    val audioOnly: Boolean = false,
    /** MIME type for DASH manifest (e.g. "video/mp4", "audio/webm"). */
    val mimeType: String = "",
    // -- DASH segment ranges (from ItagItem; 0 is the Java-side "missing"
    // default, so hasDashRanges below checks indexEnd > indexStart) --
    val initStart: Int = -1,
    val initEnd: Int = -1,
    val indexStart: Int = -1,
    val indexEnd: Int = -1,
    /** Approximate stream duration in ms; -1 when unknown. */
    val approxDurationMs: Long = -1L,
    // -- audio extras (for track selection / DASH manifest) --
    val sampleRate: Int = -1,
    val audioChannels: Int = -1,
    val audioLocale: String? = null,
    val audioTrackId: String? = null,
    val audioTrackName: String? = null,
    /** `original`, `dubbed`, `descriptive`, or `secondary`. */
    val audioTrackType: String? = null,
    /** True for the original audio track (vs. dubbed). */
    val audioTrackOriginal: Boolean = false,
    val formatKey: FormatKey? = null,
    val resourceIdentity: String? = null,
    val expiresAtMillis: Long? = null,
    @Transient val requestPlan: RequestPlan? = null,
) {
    /**
     * True when this format has a usable sidx/index range for synthetic DASH.
     *
     * Java `int` fields default to 0, so `>= 0` alone treats missing ranges as valid
     * and would wrap a muxed itag in a broken `indexRange="0-0"` DASH manifest.
     * `indexEnd > indexStart` also rejects a 1-byte index; YouTube does not emit one.
     */
    val hasDashRanges: Boolean
        get() = initStart >= 0 && initEnd >= initStart && indexEnd > indexStart
}

/** Chapter marker from Innertube `/next`. */
data class Chapter(
    val title: String = "",
    val startSeconds: Int = 0,
    val previewUrl: String? = null,
)

/**
 * Stable video fields from [Extraction.metadata].
 *
 * Count fields use `-1` when omitted (NewPipe convention).
 */
class Metadata {
    var id: String = ""
    var title: String = ""
    var author: String? = null
    var description: String? = null
    /** Length in seconds. */
    var duration: Long = 0L
    var thumbnailUrl: String? = null
    var likeCount: Long = -1L
    var dislikeCount: Long = -1L
    /** Upload time as epoch milliseconds, or null if unknown. */
    var uploadedAt: Long? = null
    var uploaderUrl: String? = null
    var uploaderAvatarUrl: String? = null
    var viewCount: Long = -1L
    /** True for live / premiere streams. */
    var isLive: Boolean = false

    fun copyFrom(other: Metadata) {
        id = other.id
        title = other.title
        author = other.author
        description = other.description
        duration = other.duration
        thumbnailUrl = other.thumbnailUrl
        likeCount = other.likeCount
        dislikeCount = other.dislikeCount
        uploadedAt = other.uploadedAt
        uploaderUrl = other.uploaderUrl
        uploaderAvatarUrl = other.uploaderAvatarUrl
        viewCount = other.viewCount
        isLive = other.isLive
    }
}

/** Formats, captions, and optional DASH/HLS URLs from [Extraction.stream]. */
data class Manifest(
    val url: String,
    val protocol: RequestPlan.Protocol,
    @Transient val requestPlan: RequestPlan,
    val expiresAtMillis: Long = Long.MAX_VALUE,
)

class Stream {
    var formats: List<Format> = emptyList()
    var subtitles: List<Subtitle> = emptyList()
    var dashUrl: String? = null
    var hlsUrl: String? = null
    @Transient var dashRequestPlan: RequestPlan? = null
    @Transient var hlsRequestPlan: RequestPlan? = null
    @Transient var manifests: List<Manifest> = emptyList()

    fun copyFrom(other: Stream) {
        formats = other.formats
        subtitles = other.subtitles
        dashUrl = other.dashUrl
        hlsUrl = other.hlsUrl
        dashRequestPlan = other.dashRequestPlan
        hlsRequestPlan = other.hlsRequestPlan
        manifests = other.manifests
    }

    /** Keep the complete source context for an already extracted fallback, without another API call. */
    fun excluding(profile: ClientProfile): Stream = Stream().also { result ->
        result.copyFrom(this)
        result.formats = formats.filter { it.requestPlan != null && it.requestPlan.profile != profile }
        result.manifests = manifests.filter { it.requestPlan.profile != profile }
        val dash = result.manifests.firstOrNull { it.protocol == RequestPlan.Protocol.DASH }
        val hls = result.manifests.firstOrNull { it.protocol == RequestPlan.Protocol.HLS }
        result.dashUrl = dash?.url; result.dashRequestPlan = dash?.requestPlan
        result.hlsUrl = hls?.url; result.hlsRequestPlan = hls?.requestPlan
    }
}

/** Chapter list from [Extraction.chapters]. */
class ChapterList {
    var chapters: List<Chapter> = emptyList()

    fun copyFrom(other: ChapterList) {
        chapters = other.chapters
    }
}

/**
 * Result of [Extractor.extract]: three independent promises for one video.
 *
 * Call [Promise.get] only on the branches you need.
 */
class Extraction(
    val videoId: String,
    val metadata: Promise<Metadata>,
    val stream: Promise<Stream>,
    val chapters: Promise<ChapterList>,
)
