package com.hhst.youtubelite.player.engine

import android.content.Context
import android.hardware.display.DisplayManager
import android.net.Uri
import android.os.Handler
import android.os.Looper
import android.os.SystemClock
import android.util.Log
import android.view.Display
import android.view.SurfaceView
import android.view.View
import androidx.media3.common.AudioAttributes
import androidx.media3.common.C
import androidx.media3.common.Format as MediaFormat
import androidx.media3.common.PlaybackException
import androidx.media3.common.Player
import androidx.media3.common.TrackSelectionOverride
import androidx.media3.common.Tracks
import androidx.media3.common.VideoSize
import androidx.media3.common.text.CueGroup
import androidx.media3.common.util.UnstableApi
import androidx.media3.datasource.HttpDataSource
import androidx.media3.exoplayer.DefaultLoadControl
import androidx.media3.exoplayer.ExoPlaybackException
import androidx.media3.exoplayer.ExoPlayer
import androidx.media3.exoplayer.analytics.AnalyticsListener
import androidx.media3.exoplayer.trackselection.DefaultTrackSelector
import com.hhst.youtubelite.R
import com.hhst.youtubelite.browser.PageKind
import com.hhst.youtubelite.core.JsonCache
import com.hhst.youtubelite.diagnostics.AppLog
import com.hhst.youtubelite.extension.ExtensionManager
import com.hhst.youtubelite.extension.PreferenceKeys
import com.hhst.youtubelite.extractor.Chapter
import com.hhst.youtubelite.extractor.Extractor
import com.hhst.youtubelite.extractor.Format
import com.hhst.youtubelite.extractor.Metadata
import com.hhst.youtubelite.extractor.OEmbedTitleFetcher
import com.hhst.youtubelite.extractor.Stream
import com.hhst.youtubelite.extractor.VideoId
import com.hhst.youtubelite.player.PREF_TTL_MS
import com.hhst.youtubelite.player.datasource.AudioTrackChoice
import com.hhst.youtubelite.player.datasource.AudioTrackIdentity
import com.hhst.youtubelite.player.datasource.CastAudioSelection
import com.hhst.youtubelite.player.datasource.CodecCapabilities
import com.hhst.youtubelite.player.datasource.MediaSourceResolver
import com.hhst.youtubelite.player.datasource.StartCappedSelectionFactory
import com.hhst.youtubelite.player.datasource.StreamSelection
import com.hhst.youtubelite.player.datasource.SubtitleSelection
import com.hhst.youtubelite.player.sponsor.SponsorBlockManager
import com.hhst.youtubelite.player.sponsor.SponsorSkipController
import java.io.IOException
import java.net.ConnectException
import java.net.NoRouteToHostException
import java.net.SocketTimeoutException
import java.util.concurrent.TimeUnit
import java.util.concurrent.atomic.AtomicLong
import kotlin.coroutines.coroutineContext
import kotlinx.coroutines.CancellationException
import kotlinx.coroutines.CompletableDeferred
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.Job
import kotlinx.coroutines.SupervisorJob
import kotlinx.coroutines.ensureActive
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import kotlinx.coroutines.sync.Mutex
import kotlinx.coroutines.sync.withLock
import kotlinx.coroutines.withContext
import kotlinx.coroutines.withTimeoutOrNull
import org.schabi.newpipe.extractor.services.youtube.streams.ClientProfile
import org.schabi.newpipe.extractor.services.youtube.streams.StreamDemand

/**
 * End-of-playback behavior behind the loop settings toggle. Only [LOOP_ONE]
 * literally loops; the QUEUE_* values advance the queue/page playlist, and
 * [PAUSE_AT_END] stops. Persisted via [persistedValue], so the ordinal and
 * value are fixed.
 */
enum class LoopMode(val persistedValue: Int, val repeatMode: Int) {
    QUEUE_NEXT(0, Player.REPEAT_MODE_OFF),
    LOOP_ONE(1, Player.REPEAT_MODE_ONE),
    PAUSE_AT_END(2, Player.REPEAT_MODE_OFF),
    QUEUE_RANDOM(3, Player.REPEAT_MODE_OFF);

    fun next(): LoopMode = when (this) {
        QUEUE_NEXT -> LOOP_ONE
        LOOP_ONE -> PAUSE_AT_END
        PAUSE_AT_END -> QUEUE_RANDOM
        QUEUE_RANDOM -> QUEUE_NEXT
    }

    companion object {
        fun fromPersisted(value: Int): LoopMode =
            entries.firstOrNull { it.persistedValue == value } ?: QUEUE_NEXT
    }
}

/** Subtitle track descriptor for the UI. */
data class SubtitleTrack(val language: String, val autoGenerated: Boolean) {
    val key: String get() = SubtitleSelection.key(language, autoGenerated)
}

/** Immutable engine state for the surface. */
data class PlaybackSnapshot(
    val videoId: String? = null,
    val url: String? = null,
    val title: String = "",
    val author: String? = null,
    val isLive: Boolean = false,
    val isPlaying: Boolean = false,
    val isBuffering: Boolean = false,
    /** Last explicit play/pause intent; independent of [isPlaying] while buffering. */
    val userWantsPlay: Boolean = false,
    val positionMs: Long = 0L,
    val durationMs: Long = 0L,
    val bufferedPositionMs: Long = 0L,
    val speed: Float = 1f,
    val loopMode: LoopMode = LoopMode.QUEUE_NEXT,
    val qualityLabel: String? = null,
    val qualities: List<String> = emptyList(),
    val subtitleKey: String? = null,
    val subtitleTracks: List<SubtitleTrack> = emptyList(),
    val audioTracks: List<AudioTrackChoice> = emptyList(),
    val audioTrackKey: String? = null,
    val sponsorSegments: List<SponsorBlockManager.Segment> = emptyList(),
    val subtitleCues: List<String> = emptyList(),
    val error: String? = null,
    val prepared: Boolean = false,
    val ended: Boolean = false,
    val videoWidth: Int = 0,
    val videoHeight: Int = 0,
    val chapters: List<Chapter> = emptyList(),
    /** Quality actually rendering (from the selected track); null = unknown. */
    val activeQuality: String? = null,
    /** True while the text renderer carries subtitles (menu highlight state). */
    val subtitleEnabled: Boolean = false,
    /** Format backing the video/audio Info rows. */
    val videoFormat: Format? = null,
    val audioFormat: Format? = null,
    /** Whole seconds left on the sponsor pre-skip card; null hides it. */
    val sponsorCountdownSec: Int? = null,
    /** Manual skip chip visible while inside a suppressed segment. */
    val sponsorChip: Boolean = false,
    /** True when [sponsorChip] targets a highlight point (chip jumps TO it). */
    val sponsorChipHighlight: Boolean = false,
    val diagnostics: PlaybackDiagnostics = PlaybackDiagnostics(),
)

/** Public player contract. */
interface PlaybackApi {
    fun preparePlayback(urlOrId: String) { }
    /** Loads a watch source; an attached receiver owns its playback controls. */
    fun play(urlOrId: String)
    /** Re-extract and reload the current video after a failure. */
    fun retry()
    fun stop()
    fun setVideoVisible(visible: Boolean) {}
    fun setVideoSurface(surface: SurfaceView?)
    fun playOrPause()
    fun play()
    fun pause()
    /** Pauses only the local player — never the cast receiver. */
    fun pauseLocal()
    /** Receiver identity after a successful recast (queue advance mid-session). */
    fun markReceiverIdentity(videoId: String, title: String, author: String?)
    fun seekTo(positionMs: Long)
    fun seekRelative(offsetMs: Long)
    fun setSpeed(speed: Float)
    /** True while a long-press 2x hold owns speed (must not persist as the user rate). */
    fun setSpeedHold(active: Boolean)
    fun setLoopMode(mode: LoopMode)
    fun setQuality(label: String?)
    /** False when [trackKey] has no parseable track; the caller keeps its UI state. */
    fun setSubtitle(trackKey: String?): Boolean
    fun setAudioTrack(trackKey: String?)
    /** Adaptive video/audio pair currently loaded, for Cast / link projection. */
    fun currentCastSource(): CastSource?
    /** Materialize file formats only when a receiver actually needs them. */
    suspend fun prepareCastSource(): CastSource? = currentCastSource()
    /** Re-extracts and returns a fresh URL for a published cast track. */
    fun refreshCastUrl(token: String, videoId: String? = null, itag: Int? = null): String?
    fun backupCastUrl(token: String, videoId: String?, itag: Int?, failedProfile: String?): String? = null
    /**
     * While [delegate] is non-null, commands and snapshot follow it.
     * Passing null detaches. Returns true when local media has already
     * diverged from the receiver (recast in flight) — the caller must not
     * seek/play the local player to the receiver's position.
     */
    fun attachCastPlayer(delegate: Player?): Boolean
    /** Queue nav buttons on the playback notification. */
    fun setQueueNavigation(hasNext: Boolean, hasPrevious: Boolean)
    /** User cancelled the pending sponsor skip (suppress that segment). */
    fun cancelSponsorSkip()
    /** Manual skip via the chip while inside a suppressed segment. */
    fun skipSponsorChipSegment()
    /**
     * Drops in-flight load/rebuild work so a close cannot be undone by a
     * late prepare. Does not clear the current media; [stop] does that.
     * [pausePlayback] false keeps the active player rolling (Cast TV) while
     * still fencing late local loads.
     */
    fun cancelPending(pausePlayback: Boolean = true)
    /** Called when the current item ends (drives queue/playlist auto-advance). */
    var onEnded: (() -> Unit)?
    /**
     * Receiver hit a playback error while delegating. The engine has already
     * detached and resumed local playback from the receiver's last position;
     * the host must end the Cast session (stopCasting + endSession) and
     * surface the failure hint.
     */
    var onCastError: (() -> Unit)?
    /**
     * Local quality/audio rebuild produced a Cast-incompatible published
     * track set: the host should load a new manifest on the receiver.
     */
    var onCastManifestReload: (() -> Unit)?
    val snapshot: StateFlow<PlaybackSnapshot>
}

/**
 * Resume-position record persisted in [JsonCache]. Duration is re-derived
 * from a fresh extraction on resume, so only the position is stored; Gson
 * ignores a stale `durationMs` field left over in previously persisted entries.
 */
data class ResumePoint(val positionMs: Long = 0L)

/** Formats + metadata the Cast proxy needs to synthesize a LAN DASH manifest. */
data class CastSource(
    val videoId: String,
    val title: String,
    val durationSec: Long,
    val video: Format?,
    val audio: Format?,
    /** Receiver OSD subtitle line; null keeps it title-only. */
    val author: String? = null,
    /** Receiver OSD artwork (public i.ytimg.com URL, fetchable by the TV). */
    val thumbnailUrl: String? = null,
)

/**
 * ExoPlayer-backed engine:
 *
 * - DASH-first assembly via [MediaSourceResolver]; muxed fallback on adaptive
 *   failure; 403 recovery by re-extraction and client demotion/exclusion.
 * - `AdaptiveTrackSelection`, capped at the start height for each new video's
 *   first chunks (no tunnelling); audio focus, wake mode,
 *   noisy-pause.
 * - 250 ms Handler ticker: position publish, SponsorBlock skip, progress
 *   persist (~1 Hz) — only while playing.
 * - STATE_ENDED: short-video replay (< 5 s); [onEnded] for queue auto-advance.
 * - Subtitle enable/track-key persisted across videos.
 */
@UnstableApi
class PlaybackEngine(
    context: Context,
    private val extractor: Extractor,
    private val resolver: MediaSourceResolver,
    private val cache: JsonCache,
    private val prefs: ExtensionManager,
    private val sponsorBlock: SponsorBlockManager,
    private val titleFetcher: OEmbedTitleFetcher? = null,
) : PlaybackApi {

    private val appContext = context.applicationContext
    private val trackSelector = DefaultTrackSelector(context, StartCappedSelectionFactory())

    private val player: ExoPlayer = ExoPlayer.Builder(context)
        .setTrackSelector(trackSelector)
        .setLoadControl(defaultLoadControl())
        .setAudioAttributes(
            AudioAttributes.Builder()
                .setUsage(C.USAGE_MEDIA)
                .setContentType(C.AUDIO_CONTENT_TYPE_MOVIE)
                .build(),
            true,
        )
            // LOCAL (not NETWORK): steady playback renders locally, and the
            // screen-off background-play path needs the CPU held through it.
            .setWakeMode(C.WAKE_MODE_LOCAL)
        .setHandleAudioBecomingNoisy(true)
        .setUsePlatformDiagnostics(false)
        .build()

    private val handler = Handler(Looper.getMainLooper())
    private val scope = CoroutineScope(SupervisorJob() + Dispatchers.Main.immediate)
    private var playJob: Job? = null
    private var firstMediaReady: CompletableDeferred<Unit>? = null
    private var rebuildJob: Job? = null
    /**
     * Last explicit play/pause from the user (or a play() load). Not inferred
     * from [Player.isPlaying]: a pause during prepare must survive the later
     * playWhenReady assignment.
     */
    @Volatile private var userWantsPlay = false
    private val playbackGeneration = AtomicLong()
    /** Generation of the media currently attached to [player]. */
    @Volatile private var attachedGeneration = 0L
    private val refreshCastMutex = Mutex()

    // refreshCastUrl (NanoHTTPD thread) reads both the fields above and the
    // flag pair below: everything crossing that thread boundary is @Volatile.
    @Volatile private var currentStream: Stream? = null
    @Volatile private var currentMetadata: Metadata? = null
    private var reExtractAttempts = 0
    /** Cheap re-extraction (same session and tokens) for stale or superseded URLs; one per video. */
    private var lightRefreshAttempts = 0
    private var backupAttempted = false

    @Volatile private var muxedFallbackActive = false
    /** Audio format of the attached source; the match key for cast switching and track recovery. */
    private var lastAudioFormat: Format? = null
    /** Video formats of the current adaptive manifest; empty when non-adaptive. */
    private var adaptiveVideoPool: List<Format> = emptyList()
    /** The user's quality pin (menu pick); null = "Auto". */
    private var pinnedQuality: String? = null
    /** Cast delegate: while non-null every command/state read goes to it. */
    private var castPlayer: Player? = null
    private var castListener: Player.Listener? = null
    /** Video the receiver is actually playing; may differ from [PlaybackSnapshot.videoId]. */
    private var receiverVideoId: String? = null
    /** True across the seek this engine issued for a sponsor skip. */
    private var skipSeekInProgress = false
    private val sponsorSkip = SponsorSkipController()

    private val _snapshot = MutableStateFlow(PlaybackSnapshot())
    override val snapshot: StateFlow<PlaybackSnapshot> = _snapshot.asStateFlow()

    override var onEnded: (() -> Unit)? = null

    override var onCastError: (() -> Unit)? = null

    override var onCastManifestReload: (() -> Unit)? = null

    /** Drives the playback notification service; injected to avoid a hard dep. */
    var notificationController: PlaybackNotificationController? = null

    private var videoVisible = true
    private var videoSurface: SurfaceView? = null
    private var outputWasVisible = false
    private var loadStartedAt = 0L
    private var firstFrameMs: Long? = null
    private var videoDecoderName: String? = null
    private var audioDecoderName: String? = null
    private val performance = PlaybackPerformanceMonitor { kind, state, fields ->
        playerLog("performance_$kind", fields + mapOf("state" to state), critical = state != "recovered")
    }
    private fun playerLog(event: String, fields: Map<String, Any?> = emptyMap(), failure: Throwable? = null, critical: Boolean = failure != null) {
        AppLog.event(AppLog.Category.PLAYER, event,
            fields + mapOf("video_id" to _snapshot.value.videoId, "operation" to playbackGeneration.get()), failure, critical)
    }
    private fun elapsed() = SystemClock.elapsedRealtime()
    private val diagnosticTicker = object : Runnable {
        override fun run() {
            runCatching { sampleDiagnostics() }
            if (_snapshot.value.videoId != null) handler.postDelayed(this, 1000)
        }
    }
    private fun sampleDiagnostics() {
        val now = elapsed()
        val counters = player.videoDecoderCounters
        counters?.ensureUpdated()
        val rendered = counters?.renderedOutputBufferCount ?: 0
        val dropped = counters?.droppedBufferCount ?: 0
        val video = player.videoFormat; val audio = player.audioFormat
        val nominal = video?.frameRate?.takeIf { it > 0 }
        val refresh = appContext.getSystemService(DisplayManager::class.java)
            ?.getDisplay(Display.DEFAULT_DISPLAY)?.refreshRate ?: 60f
        val expected = PlaybackPerformanceMonitor.expectedFps(nominal, player.playbackParameters.speed, refresh)
        val buffering = castPlayer == null && userWantsPlay &&
            (player.playbackState == Player.STATE_BUFFERING || !_snapshot.value.prepared)
        val visibleOutput = videoVisible && videoSurface?.let {
            it.isShown && it.windowVisibility == View.VISIBLE && it.holder.surface.isValid
        } == true
        if (visibleOutput != outputWasVisible) {
            outputWasVisible = visibleOutput
            performance.stabilize(now)
        }
        performance.sample(now, rendered, dropped, expected,
            visibleOutput && castPlayer == null && userWantsPlay &&
                player.playbackState == Player.STATE_READY && video != null && _snapshot.value.prepared,
            buffering)
        val diagnostics = PlaybackDiagnostics(
            nominalFps = nominal, renderedFps = performance.fps, expectedFps = expected,
            videoCodec = video?.codecs ?: video?.sampleMimeType, audioCodec = audio?.codecs ?: audio?.sampleMimeType,
            videoDecoder = videoDecoderName, audioDecoder = audioDecoderName,
            width = video?.width?.takeIf { it > 0 }, height = video?.height?.takeIf { it > 0 },
            videoBitrate = video?.bitrate?.takeIf { it > 0 }, audioBitrate = audio?.bitrate?.takeIf { it > 0 },
            renderedFrames = rendered, droppedFrames = dropped,
            droppedRatio = (rendered + dropped).takeIf { it > 0 }?.let { dropped.toFloat() / it },
            firstFrameMs = firstFrameMs, bufferingMs = performance.bufferDuration, bufferCount = performance.bufferCount,
            playbackState = when { castPlayer != null -> "cast"; buffering -> "buffering"; player.isPlaying -> "playing"; player.playbackState == Player.STATE_ENDED -> "ended"; else -> "paused" }, sampledAt = now)
        _snapshot.value = _snapshot.value.copy(diagnostics = diagnostics)
        AppLog.playerSummary = diagnostics.toString()
    }

    init {
        player.addAnalyticsListener(object : AnalyticsListener {
            override fun onVideoDecoderInitialized(eventTime: AnalyticsListener.EventTime, decoderName: String, initializedTimestampMs: Long, initializationDurationMs: Long) {
                videoDecoderName = decoderName; performance.stabilize(elapsed())
                playerLog("video_decoder", mapOf("decoder" to decoderName, "duration_ms" to initializationDurationMs))
            }
            override fun onAudioDecoderInitialized(eventTime: AnalyticsListener.EventTime, decoderName: String, initializedTimestampMs: Long, initializationDurationMs: Long) { audioDecoderName = decoderName }
        })
        resolver.configureStartupTrackSelection { trackSelector.parameters }
        // No tunneling: it is a decoder-pair constraint that
        // can silently veto track-selection changes on some devices.
        player.addListener(object : Player.Listener {
            override fun onPlaybackStateChanged(playbackState: Int) {
                publish()
                if (playbackState == Player.STATE_ENDED) handleEnded()
            }

            override fun onIsPlayingChanged(isPlaying: Boolean) {
                if (isPlaying && attachedGeneration == playbackGeneration.get()) firstMediaReady?.complete(Unit)
                handler.removeCallbacks(ticker)
                if (isPlaying) handler.post(ticker)
                else persistPosition()
                publish()
                notifyTransport(isPlaying)
            }

            override fun onRenderedFirstFrame() {
                if (firstFrameMs == null && loadStartedAt > 0 && attachedGeneration == playbackGeneration.get()) {
                    firstFrameMs = elapsed() - loadStartedAt
                    performance.stabilize(elapsed())
                    playerLog("first_frame", mapOf("duration_ms" to firstFrameMs))
                }
                if (attachedGeneration == playbackGeneration.get()) firstMediaReady?.complete(Unit)
            }

            override fun onCues(cueGroup: CueGroup) {
                val texts = cueGroup.cues.mapNotNull { it.text?.toString() }
                    .filter { it.isNotBlank() }
                if (texts != _snapshot.value.subtitleCues) {
                    _snapshot.value = _snapshot.value.copy(subtitleCues = texts)
                }
            }

            override fun onTracksChanged(tracks: Tracks) {
                performance.stabilize(elapsed())
                // Track truth drives the quality menu/badge (and re-applies
                // a pin the source swap dropped). Skipped while casting: the
                // cast player owns the visible stream then.
                if (castPlayer == null) {
                    updateQualityFromTracks()
                    publishRenditionAudio()
                }
                publish()
            }

            override fun onVideoSizeChanged(videoSize: VideoSize) {
                _snapshot.value = _snapshot.value.copy(
                    videoWidth = videoSize.width,
                    videoHeight = videoSize.height,
                )
            }

            override fun onPositionDiscontinuity(
                oldPosition: Player.PositionInfo,
                newPosition: Player.PositionInfo,
                reason: Int,
            ) {
                // Publish paused seeks too — the ticker only runs while playing.
                // A seek the engine did NOT issue is deliberate: landing inside
                // a sponsor segment opts out of auto-skipping it.
                if (reason == Player.DISCONTINUITY_REASON_SEEK) {
                    performance.stabilize(elapsed())
                    if (skipSeekInProgress) {
                        skipSeekInProgress = false
                    } else {
                        sponsorSkip.onUserSeek(
                            newPosition.positionMs.coerceAtLeast(0L),
                            sponsorBlock.currentSegments,
                        )
                    }
                }
                publish()
            }

            override fun onPlayerError(error: PlaybackException) {
                handleError(error)
            }
        })
        sponsorBlock.onSegmentsLoaded = { segments ->
            // Fired from the manager's IO scope; snapshot writes are main-confined.
            handler.post {
                _snapshot.value = _snapshot.value.copy(sponsorSegments = segments)
            }
        }
    }

    // -- ticker (250 ms skip check + position publish, persist ~1 Hz) --

    private val ticker = object : Runnable {
        private var persistTick = 0
        override fun run() {
            // Load fence: between the snapshot reset (loadInternal) and the
            // media swap the player still holds the PREVIOUS video, so running
            // skip checks against the new video's segments on the old timeline
            // would issue a bogus seek.
            if (_snapshot.value.prepared) {
                // No skipping while casting, by design: the receiver owns the
                // timeline and its seeks cannot be mirrored back with sample
                // accuracy, so SponsorBlock stays local-only.
                if (activePlayer() === player) {
                    val p = player
                    val skipTo = sponsorSkip.tick(
                        p.currentPosition, sponsorBlock.currentSegments,
                        prefs.isEnabled(PreferenceKeys.SPONSOR_COUNTDOWN),
                    )
                    if (skipTo != null) {
                        skipSeekInProgress = true
                        p.seekTo(skipTo)
                    }
                }
            }
            // Steady playback emits no listener events; without this poll the
            // time bar would freeze between buffering transitions.
            publish()
            persistTick++
            if (persistTick % 4 == 0) persistPosition()
            handler.postDelayed(this, TICK_MS)
        }
    }

    // -- load --

    override fun play(urlOrId: String) {
        if (PageKind.isShorts(urlOrId)) return
        val videoId = VideoId.parse(urlOrId) ?: return
        val requestUrl = VideoId.watchUrl(videoId)
        val explicitStart = VideoId.startPositionMs(urlOrId)
        userWantsPlay = true
        if (videoId == _snapshot.value.videoId && _snapshot.value.prepared) {
            _snapshot.value = _snapshot.value.copy(url = requestUrl)
            if (explicitStart != null) {
                seekTo(PlaybackProgress.clampStartMs(explicitStart, activePlayer().duration))
            }
            resumePlayback(activePlayer())
            return
        }
        persistPosition()
        playbackGeneration.incrementAndGet()
        playJob?.cancel()
        rebuildJob?.cancel()
        reExtractAttempts = 0
        lightRefreshAttempts = 0
        backupAttempted = false
        playJob = scope.launch {
            loadInternal(
                videoId,
                reExtract = false,
                requestUrl = requestUrl,
                startPositionMs = explicitStart,
            )
        }
    }

    override fun retry() {
        val videoId = _snapshot.value.videoId ?: return
        userWantsPlay = true
        playbackGeneration.incrementAndGet()
        playJob?.cancel()
        rebuildJob?.cancel()
        reExtractAttempts = 0
        lightRefreshAttempts = 0
        backupAttempted = false
        muxedFallbackActive = false
        playJob = scope.launch {
            loadInternal(videoId, reExtract = true, requestUrl = _snapshot.value.url)
        }
    }

    private suspend fun loadInternal(
        videoId: String,
        reExtract: Boolean,
        requestUrl: String? = null,
        startPositionMs: Long? = null,
    ) {
        val generation = playbackGeneration.get()
        loadStartedAt = elapsed(); firstFrameMs = null; videoDecoderName = null; audioDecoderName = null
        performance.reset(loadStartedAt)
        playerLog("prepare_start", mapOf("video_id" to videoId, "reextract" to reExtract))
        handler.removeCallbacks(diagnosticTicker); handler.post(diagnosticTicker)
        val speed = rememberedSpeed()
        val loop = rememberedLoopMode()
        // Selector constraints and hold state are per-video: a pin left over
        // from the previous video (or its interrupted speed hold) must not
        // apply here. The remembered quality is re-applied after resolve.
        speedHoldActive = false
        skipSeekInProgress = false
        sponsorSkip.reset()
        pinnedQuality = null
        trackSelector.parameters = trackSelector.parameters.buildUpon()
            .clearOverridesOfType(C.TRACK_TYPE_AUDIO)
            .build()
        _snapshot.value = PlaybackSnapshot(
            videoId = videoId,
            url = VideoId.watchUrl(videoId),
            isBuffering = true,
            speed = speed,
            loopMode = loop,
        )
        player.repeatMode = loop.repeatMode
        castPlayer?.repeatMode = loop.repeatMode
        try {
            val extraction = if (reExtract) extractor.extractFresh(videoId)
                else extractor.extract(videoId, demand = playbackDemand())
            val stream = withContext(Dispatchers.IO) { extraction.stream.await() }
            val metadata = withContext(Dispatchers.IO) { extraction.metadata.await() }
            coroutineContext.ensureActive()
            if (!stillCurrent(generation)) return

            muxedFallbackActive = false
            val source = withContext(Dispatchers.IO) { resolveSource(stream, metadata) }
            coroutineContext.ensureActive()
            if (!stillCurrent(generation)) return
            currentStream = stream
            currentMetadata = metadata
            lastAudioFormat = source.audioFormat
            adaptiveVideoPool = source.videoFormats
            // Clear just before the new source attaches: the old one keeps its
            // pin while the extraction runs and must not adapt up in the gap.
            clearVideoConstraints()
            applyPreferredQualityConstraint()
            sponsorBlock.load(videoId)

            val durationMs = metadata.duration * 1000L
            val startMs = PlaybackProgress.resolveStartMs(
                startPositionMs,
                rememberedPosition(videoId, metadata.duration),
                durationMs,
            )
            val mediaReady = CompletableDeferred<Unit>()
            firstMediaReady = mediaReady
            player.setMediaSource(source.mediaSource, startMs)
            player.setPlaybackSpeed(speed)
            player.prepare()
            attachedGeneration = generation
            // System media card / AVRCP read the session player's metadata;
            // PlaybackService.refresh() mirrors it into the notification too.
            // Player.mediaMetadata is read-only — title/author ride on the
            // MediaItem built by MediaSourceResolver instead.
            // While casting, the receiver keeps the audio; local stays paused
            // until the host recasts the prepared source onto the TV.
            player.playWhenReady = castPlayer == null && userWantsPlay

            // Restore persisted captions only when the key still maps to a
            // parseable track, or the badge would lie.
            val subKey = SubtitleSelection.migrate(
                rememberedSubtitleKey(),
                stream.subtitles,
            )
            if (subKey != null && resolver.hasSubtitleTrack(stream.subtitles, subKey)) {
                applySubtitle(subKey)
            }

            val audioChoices = AudioTrackIdentity.choices(stream.formats)
            _snapshot.value = _snapshot.value.copy(
                title = metadata.title,
                author = metadata.author,
                isLive = metadata.isLive,
                qualities = trackQualityLabels(),
                subtitleKey = subKey,
                subtitleTracks = stream.subtitles.map {
                    SubtitleTrack(it.languageCode, it.autoGenerated)
                },
                audioTracks = audioChoices,
                audioTrackKey = source.audioFormat?.let { AudioTrackIdentity.key(it) }
                    ?: rememberedAudioTrackKey(),
                prepared = true,
                error = null,
                chapters = emptyList(),
                videoFormat = source.videoFormat,
                audioFormat = source.audioFormat,
            )
            publishRenditionAudio()
            playerLog("prepare_ready", mapOf("duration_ms" to (elapsed() - loadStartedAt)))

            // Recast path: local is paused and the TV still holds the previous
            // video until startCasting succeeds — binding the notification now
            // would flash the new title over the old receiver. markReceiverIdentity
            // updates it after the handoff.
            if (castPlayer == null) {
                publishNotification(
                    player = activePlayer(),
                    title = metadata.title,
                    author = metadata.author,
                    videoId = videoId,
                )
            }
            maybeFetchOriginalTitle(videoId, metadata.title)
            // Publish the prepared source immediately. Optional /next must not compete
            // with initial media reads, or hold the title/controls behind chapter parsing.
            if (castPlayer != null) mediaReady.complete(Unit)
            if (withTimeoutOrNull(15_000) { mediaReady.await(); true } == true) {
                val chapters = runCatching {
                    withContext(Dispatchers.IO) { extraction.chapters.await().chapters }
                }.getOrDefault(emptyList())
                coroutineContext.ensureActive()
                if (stillCurrent(generation)) _snapshot.value = _snapshot.value.copy(chapters = chapters)
            }
        } catch (t: Throwable) {
            if (t is CancellationException) throw t
            playerLog("prepare_failed", mapOf("duration_ms" to (elapsed() - loadStartedAt)), t)
            // The previous media is still attached on failure; pausing keeps
            // its audio from running on under the new video's error screen.
            // The cast receiver is deliberately untouched: a failed local load
            // must not interrupt the session that is still playing.
            player.pause()
            _snapshot.value = _snapshot.value.copy(
                isBuffering = false,
                error = playbackFailed(t),
            )
        }
    }

    override fun stop() {
        playbackGeneration.incrementAndGet()
        userWantsPlay = false
        playJob?.cancel()
        rebuildJob?.cancel()
        persistPosition()
        receiverVideoId = null
        handler.removeCallbacks(ticker)
        handler.removeCallbacks(diagnosticTicker)
        performance.reset(elapsed())
        player.stop()
        player.clearMediaItems()
        adaptiveVideoPool = emptyList()
        pinnedQuality = null
        _snapshot.value = PlaybackSnapshot()
        attachCastPlayer(null)
        notificationController?.onStopped()
    }

    // -- surface --

    override fun setVideoVisible(visible: Boolean) {
        if (videoVisible != visible) performance.stabilize(elapsed())
        videoVisible = visible
    }

    override fun setVideoSurface(surface: SurfaceView?) {
        videoSurface = surface
        performance.stabilize(elapsed())
        player.setVideoSurfaceView(surface)
    }

    // -- controls --

    /** Receiver while attached, else local. */
    private fun activePlayer(): Player = castPlayer ?: player

    override fun playOrPause() {
        if (userWantsPlay) pause() else play()
    }

    override fun play() {
        userWantsPlay = true
        performance.stabilize(elapsed())
        playerLog("resume", mapOf("position_ms" to activePlayer().currentPosition))
        resumePlayback(activePlayer())
        notifyTransport(activePlayer().isPlaying)
    }

    override fun pause() {
        userWantsPlay = false
        playerLog("pause", mapOf("position_ms" to activePlayer().currentPosition))
        activePlayer().pause()
        notifyTransport(false)
    }

    private fun notifyTransport(isPlaying: Boolean) {
        notificationController?.onPlayingChanged(
            PlaybackTransport.showAsPlaying(userWantsPlay, isPlaying),
        )
    }

    override fun cancelPending(pausePlayback: Boolean) {
        playbackGeneration.incrementAndGet()
        if (pausePlayback) userWantsPlay = false
        playJob?.cancel()
        rebuildJob?.cancel()
        persistPosition()
        if (pausePlayback) runCatching { activePlayer().pause() }
    }

    /** Headset / notification Play and in-player resume share this path. */
    private fun resumePlayback(p: Player) {
        // Never let both ends roll: handing control to local pauses the TV,
        // and handing control back to the receiver pauses the phone.
        if (p === player) castPlayer?.pause() else player.pause()
        when {
            !_snapshot.value.prepared && _snapshot.value.videoId != null -> retry()
            _snapshot.value.error != null -> retry()
            p.playbackState == Player.STATE_ENDED -> replayFromStart(p)
            p.playerError != null -> retry()
            else -> p.play()
        }
    }

    override fun pauseLocal() { player.pause() }

    override fun markReceiverIdentity(videoId: String, title: String, author: String?) {
        receiverVideoId = videoId
        val p = castPlayer ?: return
        publishNotification(p, title, author)
    }

    /** STATE_ENDED ignores playWhenReady: rewind to 0 and start over. */
    private fun replayFromStart(p: Player) {
        // Only the local listener consumes skipSeekInProgress (in
        // onPositionDiscontinuity); the cast listener has none, so setting
        // the flag for a cast replay would leak it into the next LOCAL user
        // seek and wrongly suppress sponsorSkip.onUserSeek there.
        if (p === player) skipSeekInProgress = true
        p.seekTo(0)
        p.play()
    }

    override fun seekTo(positionMs: Long) {
        val p = activePlayer()
        val duration = p.duration
        val target = if (duration > 0) positionMs.coerceAtMost(duration) else positionMs
        p.seekTo(target.coerceAtLeast(0L))
    }

    override fun seekRelative(offsetMs: Long) {
        seekTo(activePlayer().currentPosition + offsetMs)
    }

    override fun setSpeed(speed: Float) {
        if (speed != activePlayer().playbackParameters.speed) performance.stabilize(elapsed())
        val clamped = speed.coerceIn(0.25f, 3f)
        activePlayer().setPlaybackSpeed(clamped)
        // Long-press 2x is transient: persisting it would poison the remembered
        // speed cache with a gesture the user never chose.
        if (speed != 2f || !speedHoldActive) {
            if (prefs.isEnabled(PreferenceKeys.REMEMBER_PLAYBACK_SPEED)) {
                cache.put(KEY_SPEED, clamped.toString(), PREF_TTL_MS)
            }
        }
    }

    /** True while the long-press 2x hold owns the current speed. */
    private var speedHoldActive = false

    override fun setSpeedHold(active: Boolean) {
        speedHoldActive = active
    }

    override fun setQueueNavigation(hasNext: Boolean, hasPrevious: Boolean) {
        navNextAvailable = hasNext
        notificationController?.onQueueNavigation(hasNext, hasPrevious)
    }

    override fun setLoopMode(mode: LoopMode) {
        player.repeatMode = mode.repeatMode
        castPlayer?.repeatMode = mode.repeatMode
        _snapshot.value = _snapshot.value.copy(loopMode = mode)
        cache.put(KEY_LOOP_MODE, mode.persistedValue.toString(), PREF_TTL_MS)
    }

    /**
     * Quality change. The menu entries mirror `currentTracks`, so a pick is a
     * pure track-selection change — instantaneous, keeps position and buffer —
     * on any multi-track source (synthetic pool, remote DASH, HLS). Only when
     * the source carries no choice (single representation / muxed / live /
     * pre-prepare) does it fall back to a full rebuild.
     */
    override fun setQuality(label: String?) {
        if (label == null) {
            clearVideoConstraints()
            pinnedQuality = null
            _snapshot.value = _snapshot.value.copy(qualityLabel = null)
            if (prefs.isEnabled(PreferenceKeys.REMEMBER_QUALITY)) cache.invalidate(KEY_QUALITY)
            return
        }
        if (switchQualityByTrack(label)) return
        val stream = currentStream ?: return
        val metadata = currentMetadata ?: return
        pinnedQuality = label
        if (prefs.isEnabled(PreferenceKeys.REMEMBER_QUALITY)) {
            cache.put(KEY_QUALITY, label, PREF_TTL_MS)
        }
        rebuildAtCurrentPosition(
            stream, metadata, preferredQuality = label, reloadCast = true,
        )
    }

    /**
     * Pins the video track selector to [label]'s height.
     * Returns false when the current source
     * carries no matching track and a rebuild is needed.
     *
     * While casting this pins the paused local player only — the receiver
     * keeps its current quality and the pin applies to local playback once
     * the session ends (quality picks are remembered, not pushed live).
     */
    private fun switchQualityByTrack(label: String): Boolean {
        val height = StreamSelection.parseHeight(label)
        if (height <= 0) return false
        val match = findVideoTrack(height, StreamSelection.parseFps(label)) ?: return false
        applyVideoTrackOverride(match)
        pinnedQuality = label
        _snapshot.value = _snapshot.value.copy(qualityLabel = label)
        if (prefs.isEnabled(PreferenceKeys.REMEMBER_QUALITY)) {
            cache.put(KEY_QUALITY, label, PREF_TTL_MS)
        }
        if (castPlayer != null) {
            handler.post { onCastManifestReload?.invoke() }
        }
        return true
    }

    /** One selectable video track in [player]'s current tracks. */
    private data class VideoTrackRef(
        val group: Tracks.Group,
        val index: Int,
        val format: MediaFormat,
    )

    /**
     * Best supported video track for a target height/fps: exact fps match at
     * the closest height wins.
     */
    private fun findVideoTrack(height: Int, fps: Int): VideoTrackRef? {
        var best: VideoTrackRef? = null
        var bestDelta = Int.MAX_VALUE
        var bestFpsMatch = false
        for (group in player.currentTracks.groups) {
            if (group.type != C.TRACK_TYPE_VIDEO) continue
            for (i in 0 until group.length) {
                if (!group.isTrackSupported(i)) continue
                val f = group.getTrackFormat(i)
                if (f.height <= 0) continue
                val fpsMatches = fps <= 0 || kotlin.math.round(f.frameRate).toInt() == fps
                val delta = kotlin.math.abs(f.height - height)
                if (best == null || delta < bestDelta ||
                    (delta == bestDelta && fpsMatches && !bestFpsMatch)
                ) {
                    best = VideoTrackRef(group, i, f)
                    bestDelta = delta
                    bestFpsMatch = fpsMatches
                }
            }
        }
        return best
    }

    /**
     * Drops every video constraint (overrides + size bounds). "Auto" pick, and
     * the first step of any rebuild: a leftover pin from the previous source
     * must not steer the new one.
     */
    private fun clearVideoConstraints() {
        trackSelector.parameters = trackSelector.parameters.buildUpon()
            // clearVideoSizeConstraints only resets max; min must go back to 0.
            .clearOverridesOfType(C.TRACK_TYPE_VIDEO)
            .clearVideoSizeConstraints()
            .setMinVideoSize(0, 0)
            .build()
    }

    /** Height-only pin without an explicit override; the selector adapts within it. */
    private fun pinVideoHeight(height: Int) {
        trackSelector.parameters = trackSelector.parameters.buildUpon()
            .clearOverridesOfType(C.TRACK_TYPE_VIDEO)
            .setMaxVideoSize(Int.MAX_VALUE, height)
            .setMinVideoSize(0, height)
            .build()
    }

    /** Deterministic pick: explicit override + matching size constraints. */
    private fun applyVideoTrackOverride(match: VideoTrackRef) {
        trackSelector.parameters = trackSelector.parameters.buildUpon()
            .clearOverridesOfType(C.TRACK_TYPE_VIDEO)
            .setMaxVideoSize(Int.MAX_VALUE, match.format.height)
            .setMinVideoSize(0, match.format.height)
            .setOverrideForType(TrackSelectionOverride(match.group.mediaTrackGroup, match.index))
            .build()
    }

    /**
     * Track-derived quality state after every tracks change: honest menu
     * entries, the actually-rendering label, and a re-apply of a pin the
     * source swap dropped. Guards on the closest-track height so an
     * unsatisfiable pin cannot loop.
     */
    private fun updateQualityFromTracks() {
        val active = selectedVideoTrackFormat()
        val activeLabel = active?.let {
            qualityLabelOf(it.height, kotlin.math.round(it.frameRate).toInt())
        }
        val labels = trackQualityLabels()
        var poolMatch: Format? = null
        if (active != null && adaptiveVideoPool.isNotEmpty()) {
            val fps = kotlin.math.round(active.frameRate).toInt()
            poolMatch = adaptiveVideoPool.firstOrNull {
                it.height == active.height && it.fps == fps
            } ?: adaptiveVideoPool.firstOrNull { it.height == active.height }
        }
        _snapshot.value = _snapshot.value.copy(
            qualities = labels,
            activeQuality = activeLabel,
            videoFormat = poolMatch ?: _snapshot.value.videoFormat,
        )
        val pin = pinnedQuality ?: return
        val pinHeight = StreamSelection.parseHeight(pin)
        if (pinHeight <= 0) return
        val match = findVideoTrack(pinHeight, StreamSelection.parseFps(pin)) ?: return
        if (active == null || match.format.height != active.height) {
            applyVideoTrackOverride(match)
            if (match.format.height != pinHeight) {
                // The pin is unreachable on this source: relabel to the height
                // actually pinned so badge and menu stay honest.
                val honest = qualityLabelOf(
                    match.format.height,
                    kotlin.math.round(match.format.frameRate).toInt(),
                )
                pinnedQuality = honest
                _snapshot.value = _snapshot.value.copy(qualityLabel = honest)
            }
        }
    }

    /**
     * When HLS exposes several audio renditions, those rows are the menu and a
     * pick is a track override. One player audio track leaves the extractor
     * list in place.
     */
    private fun publishRenditionAudio() {
        val choices = AudioTrackIdentity.renditionChoices(playerAudioEntries())
        // A DASH source has a single audio track, so this stays empty and the
        // extractor menu is left alone. HLS exposes one row per rendition.
        if (choices.isEmpty()) return
        val key = _snapshot.value.audioTrackKey
        val renditionKey = key?.takeIf { candidate ->
            candidate.startsWith("hls:") && choices.any { it.key == candidate }
        }
        if (choices != _snapshot.value.audioTracks || renditionKey != key) {
            _snapshot.value = _snapshot.value.copy(
                audioTracks = choices,
                audioTrackKey = renditionKey,
            )
        }
        if (renditionKey != null && selectedRenditionKey() != renditionKey) {
            applyRenditionAudio(renditionKey)
        }
    }

    private fun playerAudioEntries(): List<Pair<String?, String?>> {
        val entries = mutableListOf<Pair<String?, String?>>()
        for (group in player.currentTracks.groups) {
            if (group.type != C.TRACK_TYPE_AUDIO) continue
            for (i in 0 until group.length) {
                if (!group.isTrackSupported(i)) continue
                val format = group.getTrackFormat(i)
                entries += format.language to format.label
            }
        }
        return entries
    }

    private fun selectedRenditionKey(): String? {
        for (group in player.currentTracks.groups) {
            if (group.type != C.TRACK_TYPE_AUDIO) continue
            for (i in 0 until group.length) {
                if (!group.isTrackSelected(i)) continue
                val format = group.getTrackFormat(i)
                return AudioTrackIdentity.renditionKey(format.language, format.label)
            }
        }
        return null
    }

    private fun applyRenditionAudio(trackKey: String?) {
        val builder = trackSelector.parameters.buildUpon()
            .clearOverridesOfType(C.TRACK_TYPE_AUDIO)
            .setPreferredAudioLanguage(null)
        if (!trackKey.isNullOrBlank()) {
            val match = findRendition(trackKey) ?: return
            val language = trackKey.removePrefix("hls:").substringBefore(':')
            if (language.isNotEmpty()) builder.setPreferredAudioLanguage(language)
            builder.setOverrideForType(
                TrackSelectionOverride(match.group.mediaTrackGroup, match.index),
            )
        }
        trackSelector.parameters = builder.build()
    }

    private fun findRendition(trackKey: String): VideoTrackRef? {
        for (group in player.currentTracks.groups) {
            if (group.type != C.TRACK_TYPE_AUDIO) continue
            for (i in 0 until group.length) {
                if (!group.isTrackSupported(i)) continue
                val format = group.getTrackFormat(i)
                if (AudioTrackIdentity.renditionKey(format.language, format.label) == trackKey) {
                    return VideoTrackRef(group, i, format)
                }
            }
        }
        return null
    }

    /** Format of the currently selected video track, if any. */
    private fun selectedVideoTrackFormat(): MediaFormat? {
        for (group in player.currentTracks.groups) {
            if (group.type != C.TRACK_TYPE_VIDEO) continue
            for (i in 0 until group.length) {
                if (group.isTrackSelected(i)) return group.getTrackFormat(i)
            }
        }
        return null
    }

    /** Quality menu entries from the live tracks; pool fallback pre-prepare. */
    private fun trackQualityLabels(): List<String> {
        val labels = mutableListOf<String>()
        for (group in player.currentTracks.groups) {
            if (group.type != C.TRACK_TYPE_VIDEO) continue
            for (i in 0 until group.length) {
                if (!group.isTrackSupported(i)) continue
                val f = group.getTrackFormat(i)
                if (f.height > 0) {
                    labels += qualityLabelOf(f.height, kotlin.math.round(f.frameRate).toInt())
                }
            }
        }
        if (labels.isEmpty()) labels += adaptiveVideoPool.map {
            qualityLabelOf(it.height, it.fps)
        }
        return labels.distinct().sortedWith(
            compareByDescending<String> { StreamSelection.parseHeight(it) }
                .thenByDescending { StreamSelection.parseFps(it) },
        )
    }

    private fun qualityLabelOf(height: Int, fps: Int): String =
        "${height}p" + if (fps > 30) "$fps" else ""

    /** Audio track change: re-resolve with the chosen identity key. */
    override fun setAudioTrack(trackKey: String?) {
        if (trackKey != null) cache.put(KEY_AUDIO_TRACK, trackKey, PREF_TTL_MS)
        else cache.invalidate(KEY_AUDIO_TRACK)
        val renditionMenu = _snapshot.value.audioTracks.any { it.key.startsWith("hls:") }
        if (trackKey?.startsWith("hls:") == true || (trackKey == null && renditionMenu)) {
            _snapshot.value = _snapshot.value.copy(audioTrackKey = trackKey)
            applyRenditionAudio(trackKey)
            return
        }
        val stream = currentStream ?: return
        val metadata = currentMetadata ?: return
        rebuildAtCurrentPosition(
            stream, metadata, audioTrackKey = trackKey, reloadCast = true,
        )
    }

    /**
     * Caption selection. Off disables the text renderer but keeps the
     * remembered key so turning captions back on restores the same track.
     */
    override fun setSubtitle(trackKey: String?): Boolean {
        if (trackKey != null &&
            !resolver.hasSubtitleTrack(currentStream?.subtitles.orEmpty(), trackKey)
        ) {
            return false
        }
        if (trackKey == null) {
            cache.put(KEY_SUBTITLE_OFF, "1", PREF_TTL_MS)
            _snapshot.value = _snapshot.value.copy(subtitleKey = null)
        } else {
            cache.invalidate(KEY_SUBTITLE_OFF)
            cache.put(KEY_SUBTITLE, trackKey, PREF_TTL_MS)
            _snapshot.value = _snapshot.value.copy(subtitleKey = trackKey)
        }
        val stream = currentStream
        val metadata = currentMetadata
        if (stream != null && metadata != null && trackKey != null) {
            rebuildAtCurrentPosition(stream, metadata, subtitleKey = trackKey)
        }
        applySubtitle(trackKey)
        return true
    }

    private fun applySubtitle(trackKey: String?) {
        val iso = trackKey?.let { SubtitleSelection.languageOf(it) }
        trackSelector.parameters = trackSelector.parameters.buildUpon()
            .setPreferredTextLanguage(iso)
            .setTrackTypeDisabled(C.TRACK_TYPE_TEXT, trackKey == null)
            .build()
        _snapshot.value = _snapshot.value.copy(
            subtitleEnabled = trackKey != null,
            subtitleKey = trackKey,
        )
    }

    /** User cancelled the pre-skip card: suppress that segment for this video. */
    override fun cancelSponsorSkip() {
        sponsorSkip.cancelPending()
        updateSnapshotFromSponsor()
    }

    /** Manual skip via chip while inside a suppressed segment. */
    override fun skipSponsorChipSegment() {
        if (activePlayer() !== player) return
        val target = sponsorSkip.chipTarget(player.currentPosition, sponsorBlock.currentSegments)
        if (target != null) {
            if (sponsorSkip.chipIsHighlight) sponsorSkip.dismissHighlightChip()
            skipSeekInProgress = true
            player.seekTo(target)
        }
    }

    /**
     * Cast-friendly stream pick: H.264 MP4 + AAC decode on every receiver
     * (sidx-friendly); VP9/AV1/Opus only when nothing else matched, capped at
     * 1080p so the LAN proxy is not saturated. A muxed stream carries its own
     * audio and may serve as the video representation alone.
     */
    override fun currentCastSource(): CastSource? {
        val meta = currentMetadata ?: return null
        val id = _snapshot.value.videoId ?: return null
        // A failed load (extraction error) leaves the previous video's stream
        // data in place; casting it under the NEW id would play the old video.
        if (meta.id != id) return null
        val pool = castCandidates()
        val preferred = _snapshot.value.qualityLabel
        val avcCapped = pool.filter { isAvc(it) && it.height <= CAST_MAX_HEIGHT }
        val video = StreamSelection.selectVideo(avcCapped, preferred)
            ?: pool.firstOrNull { isAvc(it) && it.height <= CAST_MAX_HEIGHT }
            ?: pool.firstOrNull { isAvc(it) }
            ?: pool.firstOrNull { it.height <= CAST_MAX_HEIGHT }
            ?: pool.firstOrNull()
        val audio = castAudio(video)
        if (video == null || audio == null) return null
        return CastSource(
            videoId = id,
            title = meta.title.ifBlank { _snapshot.value.title },
            durationSec = meta.duration,
            video = video,
            audio = if (audio == video) null else audio,
            author = meta.author,
            // Public CDN URL: images need no CORS and the receiver fetches it
            // directly — routing it through the LAN proxy would add nothing.
            thumbnailUrl = VideoId.thumbnailUrl(id),
        )
    }

    override suspend fun prepareCastSource(): CastSource? {
        currentCastSource()?.let { return it }
        val id = _snapshot.value.videoId ?: return null
        val generation = playbackGeneration.get()
        val media = try { withContext(Dispatchers.IO) { extractor.awaitMedia(id) } }
            catch (cancelled: CancellationException) { throw cancelled }
            catch (_: Exception) { return null }
        if (!stillCurrent(generation) || _snapshot.value.videoId != id || media.first.id != id) return null
        currentStream = media.second
        return currentCastSource()
    }

    /**
     * Video pool for casting: the manifest pool when present, else muxed. All
     * entries carry sidx ranges — without them the receiver cannot address
     * segments and downloads the whole stream.
     */
    private fun castCandidates(): List<Format> =
        (adaptiveVideoPool.ifEmpty {
            currentStream?.formats?.filter { it.videoOnly }
                ?.ifEmpty { currentStream?.formats?.filter(StreamSelection::isMuxed).orEmpty() }
                ?: emptyList()
        }).filter { it.hasDashRanges }

    /**
     * Audio for casting: current identity first, then AAC (default receivers
     * cannot decode Opus). A muxed candidate needs no separate audio.
     */
    private fun castAudio(video: Format?): Format? {
        if (video != null && !video.videoOnly) return video
        val audioOnly = currentStream?.formats?.filter { it.audioOnly && it.hasDashRanges }
            ?.ifEmpty { listOfNotNull(lastAudioFormat).filter { it.hasDashRanges } }
            .orEmpty()
        val preferredKey = lastAudioFormat?.let { AudioTrackIdentity.key(it) }
            ?: _snapshot.value.audioTrackKey
        return CastAudioSelection.select(audioOnly, preferredKey, ::isAac)
    }

    private fun isAvc(f: Format): Boolean =
        f.mimeType.contains("avc", true) || (f.codec ?: "").startsWith("avc")

    private fun isAac(f: Format): Boolean =
        f.mimeType.contains("mp4a", true) || (f.codec ?: "").startsWith("mp4a")

    /** While casting, all playback commands and state reads route to [delegate]. */
    override fun attachCastPlayer(delegate: Player?): Boolean {
        val keepLocal = localDivergedFromReceiver() && delegate == null
        // The listener lives on the CAST player; removing it from the local
        // one is a silent no-op and leaks one listener per session.
        castListener?.let { l -> runCatching { castPlayer?.removeListener(l) } }
        castListener = null
        castPlayer = delegate
        skipSeekInProgress = false
        sponsorSkip.reset()
        if (delegate == null) {
            receiverVideoId = null
            handler.removeCallbacks(ticker)
            if (player.isPlaying) handler.post(ticker)
            publishNotification(player)
            publish()
            return keepLocal
        }
        receiverVideoId = _snapshot.value.videoId
        val listener = object : Player.Listener {
            override fun onIsPlayingChanged(isPlaying: Boolean) {
                if (localDivergedFromReceiver()) return
                handler.removeCallbacks(ticker)
                if (isPlaying) handler.post(ticker)
                else persistPosition()
                publish()
                notifyTransport(isPlaying)
            }

            override fun onPlaybackStateChanged(playbackState: Int) {
                if (localDivergedFromReceiver()) return
                publish()
                if (playbackState == Player.STATE_ENDED) handleEnded()
            }

            override fun onPlayerError(error: PlaybackException) {
                if (castPlayer == null) return
                val pos = castPlayer?.currentPosition ?: 0L
                val keepLocal = attachCastPlayer(null)
                if (!keepLocal) {
                    if (pos > 0L) seekTo(pos)
                    play()
                }
                onCastError?.invoke()
            }
        }
        delegate.addListener(listener)
        castListener = listener
        delegate.repeatMode = _snapshot.value.loopMode.repeatMode
        delegate.setPlaybackSpeed(player.playbackParameters.speed)
        // Local surface blacks out; keep it paused and silent.
        player.pause()
        // The notification/MediaSession must follow the delegation too, or
        // headset keys and the play state keep driving the paused local player.
        publishNotification(delegate)
        publish()
        return false
    }

    /**
     * Re-extracts [videoId] (the published proxy identity, not necessarily
     * the phone's current media) and returns a fresh URL for token "v"/"a".
     */
    override fun refreshCastUrl(token: String, videoId: String?, itag: Int?): String? {
        val id = videoId ?: _snapshot.value.videoId ?: return null
        return runCatching {
            runBlocking {
                refreshCastMutex.withLock {
                    val fresh = withTimeoutOrNull(45_000) {
                        withContext(Dispatchers.IO) {
                            val extracted = extractor.extractFresh(id).stream.await()
                            val url = pickPublishedUrl(extracted, token, itag)
                            val localMeta = currentMetadata
                            val source = if (localMeta != null && localMeta.id == id) {
                                resolveSource(extracted, localMeta)
                            } else {
                                null
                            }
                            handler.post {
                                if (_snapshot.value.videoId == id) {
                                    currentStream = extracted
                                    if (source != null) {
                                        lastAudioFormat = source.audioFormat
                                        adaptiveVideoPool = source.videoFormats
                                    }
                                }
                            }
                            url
                        }
                    }
                    fresh
                }
            }
        }.getOrNull()
    }

    override fun backupCastUrl(token: String, videoId: String?, itag: Int?, failedProfile: String?): String? {
        if (currentMetadata?.id != videoId) return null
        val profile = ClientProfile.values().firstOrNull { it.name == failedProfile } ?: return null
        val stream = currentStream ?: return null
        return pickPublishedUrl(stream.excluding(profile), token, itag)
    }

    private fun pickPublishedUrl(stream: Stream, token: String, itag: Int?): String? {
        val previous = if (token == "a") lastAudioFormat else _snapshot.value.videoFormat?.takeIf { itag == null || it.itag == itag }
        if (previous?.formatKey != null) {
            if (previous.resourceIdentity.isNullOrBlank()) return null
            return stream.formats.firstOrNull { it.formatKey == previous.formatKey && it.resourceIdentity == previous.resourceIdentity }?.url
        }
        if (itag != null) {
            stream.formats.filter { it.itag == itag }.distinctBy { it.audioTrackId to it.codec }.singleOrNull()?.url?.let { return it }
        }
        return stream.formats.firstOrNull {
            if (token == "a") it.audioOnly else !it.audioOnly
        }?.url
    }

    /**
     * Applies the remembered quality as track-selection constraints after a
     * fresh adaptive resolve. A new player/selector starts unconstrained, so
     * without this the first frames would render at the pool's top quality
     * before any later constraint lands.
     */
    private fun applyPreferredQualityConstraint() {
        val label = rememberedQuality() ?: return
        val height = StreamSelection.parseHeight(label)
        if (height <= 0) return
        // HLS now supplies rendition tracks without materializing file formats.
        // Pin before prepare as well, so the automatic startup cap cannot replace
        // the remembered manual height on its first frame.
        val hls = !muxedFallbackActive && !currentStream?.hlsUrl.isNullOrBlank()
        if (adaptiveVideoPool.isEmpty() && !hls) return
        if (adaptiveVideoPool.isNotEmpty() && adaptiveVideoPool.none { it.height == height }) return
        pinnedQuality = label
        pinVideoHeight(height)
        // The selector is hard-pinned; the badge must not claim "Auto".
        _snapshot.value = _snapshot.value.copy(qualityLabel = label)
    }

    /** Single resolve entry point for both load and cast-refresh paths. */
    private fun resolveSource(
        stream: Stream,
        metadata: Metadata,
    ): MediaSourceResolver.Resolved = resolver.resolve(
        stream, metadata,
        preferredQuality = rememberedQuality(),
        audioTrackKey = rememberedAudioTrackKey(),
        forceMuxed = muxedFallbackActive,
        subtitleKey = rememberedSubtitleKey(),
    )

    // -- end-of-playback --

    /** Mirrors the nav availability the VM pushes (queue next / page playlist). */
    private var navNextAvailable = true

    private fun handleEnded() {
        if (playJob?.isActive == true || rebuildJob?.isActive == true) return
        if (attachedGeneration != playbackGeneration.get()) return
        persistPosition()
        val p = activePlayer()
        val duration = p.duration
        when (_snapshot.value.loopMode) {
            LoopMode.LOOP_ONE -> Unit // REPEAT_MODE_ONE already replays
            LoopMode.PAUSE_AT_END -> Unit // stay ended
            // Queue/page-playlist advancement wins over the loop below; a
            // short video with nothing to advance to just replays.
            LoopMode.QUEUE_NEXT, LoopMode.QUEUE_RANDOM -> {
                if (localDivergedFromReceiver()) return
                if (duration in 1 until PlaybackProgress.SAFE_ZONE_MS && !navNextAvailable) {
                    replayFromStart(p)
                    return
                }
                onEnded?.invoke()
            }
        }
    }

    // -- error recovery --

    private fun handleError(error: PlaybackException) {
        playerLog("playback_error", mapOf("error_code" to error.errorCode, "position_ms" to player.currentPosition), error)
        if (attachedGeneration != playbackGeneration.get()) return
        val videoId = _snapshot.value.videoId
        val metadata = currentMetadata
        // Ownership: an error fired from media a pending load is replacing
        // (old video still attached) must not drive recovery — same
        // metadata/snapshot identity guard as refreshCastUrl.
        if (metadata != null && metadata.id != videoId) return
        if (isTextRendererError(error)) {
            recoverFromTextError()
            return
        }
        var reason = recoveryReason(error)
        val stream = currentStream

        // Expired or superseded URLs (not a server refusal) first get a cheap re-extraction with the
        // current session and tokens: no page request, no minter reset. It does not use up the
        // full-refresh budget; if it was already spent the failure is handled as a 403.
        if (reason == RecoveryReason.URL_STALE) {
            if (lightRefreshAttempts < MAX_LIGHT_REFRESH_ATTEMPTS && videoId != null) {
                lightRefreshAttempts++
                val position = player.currentPosition
                playbackGeneration.incrementAndGet()
                playJob?.cancel()
                rebuildJob?.cancel()
                playJob = scope.launch {
                    _snapshot.value = _snapshot.value.copy(isBuffering = true, error = null)
                    skipSeekInProgress = true
                    withContext(Dispatchers.IO) { extractor.invalidateStream(videoId) }
                    loadInternal(
                        videoId, reExtract = false,
                        requestUrl = _snapshot.value.url,
                        startPositionMs = position,
                    )
                }
                return
            }
            reason = RecoveryReason.HTTP_403
        }

        if (reason == RecoveryReason.HTTP_403 && reExtractAttempts >= 1 && !backupAttempted && stream != null && metadata != null) {
            backupAttempted = true
            val failedUri = failingUri(error)
            val failedItag = failedUri?.getQueryParameter("itag")?.toIntOrNull()
            val failedFormat = listOfNotNull(_snapshot.value.videoFormat, lastAudioFormat).firstOrNull {
                failedItag == null || it.itag == failedItag
            } ?: stream.formats.firstOrNull { it.url == failedUri?.toString() }
            val profile = failedFormat?.requestPlan?.profile ?: if (metadata.isLive)
                (stream.dashRequestPlan ?: stream.hlsRequestPlan)?.profile
                else (stream.hlsRequestPlan ?: stream.dashRequestPlan)?.profile
            val backup = profile?.let(stream::excluding)
            if (backup != null && runCatching { resolveSource(backup, metadata) }.isSuccess) {
                currentStream = backup
                rebuildAtCurrentPosition(backup, metadata, startMs = player.currentPosition, reloadCast = true)
                return
            }
        }

        // Adaptive failure → muxed only if a muxed itag the resolver would
        // actually select can play (sidx ranges or a poToken). VR formats are
        // excluded by preferPlayable; counting them viable makes the forceMuxed
        // rebuild throw instead of reaching the re-extract recovery below.
        if (reason == RecoveryReason.CONNECTION_OPEN_FAILED && !muxedFallbackActive && stream != null && metadata != null) {
            val muxedViable = stream.formats.any {
                StreamSelection.isMuxed(it) && !StreamSelection.isAndroidVr(it) &&
                    (it.requestPlan != null || it.hasDashRanges || it.url.contains("&pot="))
            }
            if (muxedViable) {
                val position = player.currentPosition
                muxedFallbackActive = true
                rebuildAtCurrentPosition(stream, metadata, forceMuxed = true, startMs = position, reloadCast = true)
                return
            }
        }

        // One full session/token refresh, followed by one existing compatible backup.
        if (reason == RecoveryReason.HTTP_403 &&
            reExtractAttempts < MAX_REEXTRACT_ATTEMPTS &&
            videoId != null
        ) {
            reExtractAttempts++
            muxedFallbackActive = false
            val position = player.currentPosition
            playbackGeneration.incrementAndGet()
            playJob?.cancel()
            rebuildJob?.cancel()
            playJob = scope.launch {
                _snapshot.value = _snapshot.value.copy(isBuffering = true, error = null)
                skipSeekInProgress = true
                loadInternal(
                    videoId, reExtract = true,
                    requestUrl = _snapshot.value.url,
                    startPositionMs = position,
                )
            }
            return
        }

        _snapshot.value = _snapshot.value.copy(
            isBuffering = false,
            // play()/playOrPause() check this to reload instead of issuing a
            // no-op playWhenReady against an idle-with-error player.
            prepared = false,
            error = playbackFailed(error),
        )
    }

    private fun recoveryReason(error: PlaybackException): RecoveryReason? {
        var cause: Throwable? = error
        while (cause != null) {
            if (cause is IOException && cause.message in setOf("MEDIA_SESSION_CHANGED", "MEDIA_OBJECT_CHANGED", "MEDIA_URL_EXPIRED")) return RecoveryReason.URL_STALE
            when (cause) {
                is HttpDataSource.InvalidResponseCodeException ->
                    if (cause.responseCode == 403) return RecoveryReason.HTTP_403
                is HttpDataSource.HttpDataSourceException ->
                    if (cause.type == HttpDataSource.HttpDataSourceException.TYPE_OPEN &&
                        (cause.cause is SocketTimeoutException ||
                            cause.cause is ConnectException ||
                            cause.cause is NoRouteToHostException)
                    ) return RecoveryReason.CONNECTION_OPEN_FAILED
            }
            cause = cause.cause
        }
        return null
    }

    /** The 403'd googlevideo URI, or null. */
    private fun failingUri(error: PlaybackException): Uri? {
        var cause: Throwable? = error
        while (cause != null) {
            if (cause is HttpDataSource.InvalidResponseCodeException) {
                return cause.dataSpec.uri
            }
            cause = cause.cause
        }
        return null
    }

    private fun isTextRendererError(error: PlaybackException): Boolean {
        val exo = error as? ExoPlaybackException
        if (exo != null && exo.type == ExoPlaybackException.TYPE_RENDERER) {
            val mime = exo.rendererFormat?.sampleMimeType.orEmpty()
            if (mime.startsWith("text/") ||
                mime.contains("ttml", ignoreCase = true) ||
                mime.contains("x-media3-cues", ignoreCase = true)
            ) {
                return true
            }
            if (exo.rendererName?.contains("Text", ignoreCase = true) == true) return true
        }
        var cause: Throwable? = error
        while (cause != null) {
            val msg = cause.message.orEmpty()
            if (msg.contains("Legacy decoding is disabled", ignoreCase = true) ||
                msg.contains("application/ttml+xml", ignoreCase = true) ||
                msg.contains("application/x-media3-cues", ignoreCase = true)
            ) {
                return true
            }
            cause = cause.cause
        }
        return false
    }

    /** Drop captions and keep A/V playing after a TTML/cue renderer failure. */
    private fun recoverFromTextError() {
        // Disable TEXT first; re-prepare can otherwise retry the same samples
        // and crash again while ExoPlayer tries to disable the text renderer.
        runCatching { applySubtitle(null) }
        val position = player.currentPosition.coerceAtLeast(0L)
        if (player.playerError != null) {
            runCatching {
                skipSeekInProgress = true
                player.prepare()
                player.seekTo(position)
                player.playWhenReady = userWantsPlay && castPlayer == null
            }
        }
    }

    private enum class RecoveryReason { HTTP_403, URL_STALE, CONNECTION_OPEN_FAILED }

    // -- rebuild (quality/audio/fallback) --

    private fun rebuildAtCurrentPosition(
        stream: Stream,
        metadata: Metadata,
        preferredQuality: String? = _snapshot.value.qualityLabel,
        audioTrackKey: String? = _snapshot.value.audioTrackKey,
        forceMuxed: Boolean = muxedFallbackActive,
        startMs: Long = player.currentPosition,
        subtitleKey: String? = _snapshot.value.subtitleKey,
        reloadCast: Boolean = false,
    ) {
        val speed = activePlayer().playbackParameters.speed
        if (preferredQuality != null) pinnedQuality = preferredQuality
        val generation = playbackGeneration.incrementAndGet()
        rebuildJob?.cancel()
        rebuildJob = scope.launch {
            _snapshot.value = _snapshot.value.copy(isBuffering = true)
            try {
                val source = withContext(Dispatchers.IO) {
                    resolver.resolve(
                        stream, metadata, preferredQuality, audioTrackKey, forceMuxed,
                        subtitleKey,
                    )
                }
                coroutineContext.ensureActive()
                if (!stillCurrent(generation)) return@launch
                // Clear just before the swap: the old source keeps playing (and
                // its pin) while the resolve runs and must not adapt up in the gap.
                clearVideoConstraints()
                player.setMediaSource(source.mediaSource, startMs)
                player.setPlaybackSpeed(speed)
                player.prepare()
                attachedGeneration = generation
                // A rebuild while casting retargets the paused local player
                // only (quality/audio picks are remembered and take effect
                // when the session ends); the receiver keeps playing until
                // onCastManifestReload recasts.
                player.playWhenReady = castPlayer == null && userWantsPlay
                lastAudioFormat = source.audioFormat
                adaptiveVideoPool = source.videoFormats
                // Re-apply the pin after the source swap; onTracksChanged then
                // publishes the honest badge from the actually selected track.
                // A pin the new source cannot deliver (muxed fallback, shrunken
                // pool) must not keep claiming it does.
                var honored: String? = null
                if (preferredQuality != null) {
                    val h = StreamSelection.parseHeight(preferredQuality)
                    if (h > 0 && adaptiveVideoPool.any { it.height == h }) {
                        pinVideoHeight(h)
                        honored = preferredQuality
                    }
                }
                pinnedQuality = honored
                val audioChoices = AudioTrackIdentity.choices(stream.formats)
                _snapshot.value = _snapshot.value.copy(
                    qualityLabel = honored,
                    audioTrackKey = source.audioFormat?.let { AudioTrackIdentity.key(it) }
                        ?: audioTrackKey,
                    audioTracks = audioChoices,
                    subtitleKey = subtitleKey,
                    isBuffering = false,
                    error = null,
                    videoFormat = source.videoFormat,
                    audioFormat = source.audioFormat,
                )
                publishRenditionAudio()
                if (reloadCast && castPlayer != null) {
                    handler.post { onCastManifestReload?.invoke() }
                }
            } catch (t: Throwable) {
                if (t is CancellationException) throw t
                _snapshot.value = _snapshot.value.copy(isBuffering = false, error = playbackFailed(t))
            }
        }
    }

    /**
     * `use_original_title`: swaps the localized title for the oEmbed canonical
     * one. Off-main fetch; a stale result is dropped when the video changed.
     */
    private fun maybeFetchOriginalTitle(videoId: String, localizedTitle: String) {
        val fetcher = titleFetcher ?: return
        if (!prefs.isEnabled(PreferenceKeys.USE_ORIGINAL_TITLE)) return
        if (localizedTitle.isBlank()) return
        scope.launch {
            val original = withContext(Dispatchers.IO) { fetcher.fetchOriginalTitle(videoId) }
            if (original != null &&
                videoId == _snapshot.value.videoId &&
                original != _snapshot.value.title
            ) {
                _snapshot.value = _snapshot.value.copy(title = original)
                // Recast in flight: the receiver still plays the previous
                // video — don't flash this title onto its notification.
                publishNotification(activePlayer(), title = original)
            }
        }
    }

    // -- persistence helpers --

    private fun persistPosition() {
        // Load fence: with a load in flight the snapshot's videoId is the NEW
        // video while position/duration still come from the old player —
        // persisting would write the old position under the new video's key.
        if (!_snapshot.value.prepared) return
        val videoId = _snapshot.value.videoId ?: return
        val p = if (localDivergedFromReceiver()) player else activePlayer()
        val ended = p.playbackState == Player.STATE_ENDED
        when (PlaybackProgress.write(p.currentPosition, p.duration, ended)) {
            PlaybackProgress.Write.CLEAR -> cache.invalidate(progressKey(videoId))
            PlaybackProgress.Write.SAVE ->
                if (prefs.isEnabled(PreferenceKeys.REMEMBER_LAST_POSITION)) {
                    cache.put(
                        progressKey(videoId),
                        ResumePoint(p.currentPosition),
                        PROGRESS_TTL_MS,
                    )
                }
            PlaybackProgress.Write.SKIP -> Unit
        }
    }

    private fun rememberedSpeed(): Float =
        if (prefs.isEnabled(PreferenceKeys.REMEMBER_PLAYBACK_SPEED)) {
            cache.get(KEY_SPEED, String::class.java)?.toFloatOrNull() ?: 1f
        } else 1f

    private fun rememberedLoopMode(): LoopMode =
        cache.get(KEY_LOOP_MODE, String::class.java)
            ?.toIntOrNull()
            ?.let(LoopMode::fromPersisted)
            ?: LoopMode.QUEUE_NEXT

    private fun rememberedQuality(): String? =
        if (prefs.isEnabled(PreferenceKeys.REMEMBER_QUALITY)) {
            cache.get(KEY_QUALITY, String::class.java)
        } else null

    private fun playbackDemand() = StreamDemand(
        rememberedQuality()?.let(StreamSelection::parseHeight) ?: 0,
        rememberedAudioTrackKey()?.takeIf { it.startsWith("id:") }?.removePrefix("id:"), false,
        setOf("avc", "vp9", "vp09", "hvc", "hev") +
            if (CodecCapabilities.isDecodable(
                    Format(codec = "av01", height = 1080))) setOf("av01") else emptySet())

    override fun preparePlayback(urlOrId: String) {
        if (PageKind.isShorts(urlOrId)) return
        extractor.preparePlayback(urlOrId, playbackDemand())
    }

    private fun rememberedSubtitleKey(): String? {
        if (cache.get(KEY_SUBTITLE_OFF, String::class.java) != null) return null
        return cache.get(KEY_SUBTITLE, String::class.java)
    }

    private fun rememberedAudioTrackKey(): String? =
        cache.get(KEY_AUDIO_TRACK, String::class.java)

    private fun rememberedPosition(videoId: String, durationSec: Long): Long {
        if (!prefs.isEnabled(PreferenceKeys.REMEMBER_LAST_POSITION)) return 0L
        val point = cache.get(progressKey(videoId), ResumePoint::class.java) ?: return 0L
        val durationMs = durationSec * 1000
        return if (point.positionMs > PlaybackProgress.SAFE_ZONE_MS &&
            (durationMs <= 0 || point.positionMs < durationMs - PlaybackProgress.SAFE_ZONE_MS)
        ) point.positionMs else 0L
    }

    private fun publish() {
        // Load fence: while a load is in flight the snapshot already carries
        // the NEW video id but the player still holds the previous one —
        // publishing here would label the old timeline/duration with the new
        // id (and hide the loading spinner). Listeners and the ticker both
        // route through this single gate.
        if (!_snapshot.value.prepared) return
        val p = if (localDivergedFromReceiver()) player else activePlayer()
        val s = _snapshot.value
        _snapshot.value = s.copy(
            isPlaying = p.isPlaying,
            isBuffering = p.playbackState == Player.STATE_BUFFERING,
            userWantsPlay = userWantsPlay,
            positionMs = p.currentPosition.coerceAtLeast(0L),
            durationMs = p.duration.takeIf { it > 0 } ?: 0L,
            bufferedPositionMs = p.bufferedPosition.coerceAtLeast(0L),
            speed = p.playbackParameters.speed,
            ended = p.playbackState == Player.STATE_ENDED,
            sponsorCountdownSec = sponsorSkip.countdownSec,
            sponsorChip = sponsorSkip.chipActive,
            sponsorChipHighlight = sponsorSkip.chipIsHighlight,
        )
    }

    private fun updateSnapshotFromSponsor() {
        val s = _snapshot.value
        if (s.sponsorCountdownSec != sponsorSkip.countdownSec ||
            s.sponsorChip != sponsorSkip.chipActive ||
            s.sponsorChipHighlight != sponsorSkip.chipIsHighlight
        ) {
            _snapshot.value = s.copy(
                sponsorCountdownSec = sponsorSkip.countdownSec,
                sponsorChip = sponsorSkip.chipActive,
                sponsorChipHighlight = sponsorSkip.chipIsHighlight,
            )
        }
    }

    private fun stillCurrent(generation: Long): Boolean =
        generation == playbackGeneration.get()

    private fun publishNotification(
        player: Player,
        title: String = _snapshot.value.title,
        author: String? = _snapshot.value.author,
        videoId: String? = _snapshot.value.videoId,
    ) {
        if (castPlayer != null &&
            receiverVideoId != null && receiverVideoId != _snapshot.value.videoId
        ) {
            return
        }
        val id = videoId ?: return
        notificationController?.onLoaded(player, title, author, VideoId.thumbnailUrl(id))
    }

    /** Local media is a different video than the one the receiver is playing. */
    private fun localDivergedFromReceiver(): Boolean {
        val id = _snapshot.value.videoId ?: return false
        val recv = receiverVideoId ?: return false
        return id != recv
    }

    private fun playbackFailed(t: Throwable): String {
        Log.w(TAG, "playback failed", t)
        return appContext.getString(R.string.player_error)
    }

    companion object {
        private const val TAG = "PlaybackEngine"
        private const val TICK_MS = 250L
        private const val CAST_MAX_HEIGHT = 1080
        private val PROGRESS_TTL_MS = TimeUnit.DAYS.toMillis(3)
        private const val MAX_REEXTRACT_ATTEMPTS = 1
        private const val MAX_LIGHT_REFRESH_ATTEMPTS = 1
        private const val KEY_SPEED = "player:speed"
        private const val KEY_QUALITY = "player:quality"
        private const val KEY_LOOP_MODE = "player:loop_mode"
        private const val KEY_SUBTITLE = "player:subtitle_language"
        private const val KEY_SUBTITLE_OFF = "player:subtitle_off"
        private const val KEY_AUDIO_TRACK = "player:audio_language"
        private fun progressKey(videoId: String) = "player:progress:$videoId"
    }
}

/** Bound compressed samples too: a 50 s high-bitrate buffer can exhaust a 256 MB heap. */
internal fun mediaBufferBudgetBytes(maxHeapBytes: Long): Int =
    (maxHeapBytes / 8).coerceIn(16L * 1024 * 1024, 64L * 1024 * 1024).toInt()

/** Keep the time windows, but let the byte budget stop high-bitrate read-ahead. */
@UnstableApi
internal fun defaultLoadControl(): DefaultLoadControl = DefaultLoadControl.Builder()
    .setBufferDurationsMs(50_000, 60_000, 500, 4_000)
    .setTargetBufferBytes(mediaBufferBudgetBytes(Runtime.getRuntime().maxMemory()))
    .setPrioritizeTimeOverSizeThresholds(false)
    .build()
