package com.hhst.youtubelite.downloader.resolve

import com.hhst.youtubelite.extractor.Format
import com.hhst.youtubelite.extractor.Subtitle

const val TEST_VIDEO_ID = "abcdefghijk"

fun playbackUrl(
    itag: Int,
    clen: Long = 1_000_000,
    client: String = "VISIONOS",
    extra: String = "",
    id: String = "mediaid",
): String =
    "https://rr.googlevideo.com/videoplayback?id=$id&itag=$itag&clen=$clen&c=$client" +
        "&expire=999999&pot=oldtoken&rn=1$extra"

fun videoFormat(
    height: Int,
    codec: String = "avc1.640028",
    itag: Int = height,
    bitrate: Int = 5_000_000,
    fps: Int = 30,
    container: String = "MPEG_4",
    clen: Long = height * 10_000L,
    client: String = "VISIONOS",
): Format = Format(
    url = playbackUrl(itag, clen, client),
    height = height,
    width = height * 16 / 9,
    bitrate = bitrate,
    fps = fps,
    qualityLabel = "${height}p",
    codec = codec,
    container = container,
    itag = itag,
    videoOnly = true,
    mimeType = "video/mp4",
    approxDurationMs = 60_000,
)

fun audioFormat(
    language: String = "en",
    original: Boolean = true,
    bitrate: Int = 128_000,
    codec: String = "mp4a.40.2",
    itag: Int = 140,
    trackId: String? = language,
    trackType: String? = when {
        original -> "original"
        else -> "dubbed"
    },
    clen: Long = 200_000,
): Format = Format(
    url = playbackUrl(itag, clen),
    bitrate = bitrate,
    codec = codec,
    container = "MPEG_4",
    itag = itag,
    audioOnly = true,
    mimeType = "audio/mp4",
    approxDurationMs = 60_000,
    audioLocale = language,
    audioTrackId = trackId,
    audioTrackType = trackType,
    audioTrackOriginal = original,
)

fun muxedFormat(height: Int = 360, itag: Int = 18, client: String = "ANDROID"): Format = Format(
    url = playbackUrl(itag, clen = 500_000, client = client),
    height = height,
    width = 640,
    bitrate = 1_000_000,
    codec = "avc1.42001E",
    container = "MPEG_4",
    itag = itag,
    mimeType = "video/mp4",
    approxDurationMs = 60_000,
)

fun subtitle(
    language: String,
    mime: String = "text/vtt",
    auto: Boolean = false,
): Subtitle = Subtitle(
    url = "https://www.youtube.com/api/timedtext?lang=$language&fmt=vtt",
    languageCode = language,
    autoGenerated = auto,
    mimeType = mime,
)

fun catalog(
    formats: List<Format>,
    subtitles: List<Subtitle> = emptyList(),
    isLive: Boolean = false,
    durationSec: Long = 60L,
    thumbnailUrl: String? = "https://i.ytimg.com/vi/$TEST_VIDEO_ID/hqdefault.jpg",
): DownloadCatalog = DownloadCatalog(
    videoId = TEST_VIDEO_ID,
    title = "Sample",
    durationSec = durationSec,
    isLive = isLive,
    thumbnailUrl = thumbnailUrl,
    formats = formats,
    subtitles = subtitles,
)
