package com.hhst.youtubelite.player.datasource

import com.hhst.youtubelite.extractor.Subtitle
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

class SubtitleSelectionTest {

    private val humanEn = Subtitle(url = "en-h", languageCode = "en", autoGenerated = false, mimeType = "text/vtt")
    private val autoEn = Subtitle(url = "en-a", languageCode = "en", autoGenerated = true, mimeType = "text/vtt")
    private val humanEs = Subtitle(url = "es-h", languageCode = "es", autoGenerated = false, mimeType = "text/vtt")

    @Test
    fun keySelectsAutoEvenWhenHumanExists() {
        val picked = SubtitleSelection.select(listOf(humanEn, autoEn), SubtitleSelection.key("en", true))
        assertEquals(listOf(autoEn), picked)
    }

    @Test
    fun keySelectsHumanTrack() {
        val picked = SubtitleSelection.select(listOf(humanEn, autoEn), SubtitleSelection.key("en", false))
        assertEquals(listOf(humanEn), picked)
    }

    @Test
    fun legacyLanguagePrefersHuman() {
        val picked = SubtitleSelection.select(listOf(autoEn, humanEn), "en")
        assertEquals(listOf(humanEn), picked)
    }

    @Test
    fun legacyLanguageFallsBackToAuto() {
        val picked = SubtitleSelection.select(listOf(autoEn), "en")
        assertEquals(listOf(autoEn), picked)
    }

    @Test
    fun migrateLegacyLanguageToHumanKey() {
        val key = SubtitleSelection.migrate("en", listOf(humanEn, autoEn, humanEs))
        assertEquals("en|manual", key)
    }

    @Test
    fun blankPreferredSelectsNothing() {
        assertTrue(SubtitleSelection.select(listOf(humanEn), null).isEmpty())
        assertTrue(SubtitleSelection.select(listOf(humanEn), "").isEmpty())
    }
}
