package com.hhst.youtubelite.player.surface

import androidx.compose.foundation.background
import androidx.compose.foundation.basicMarquee
import androidx.compose.foundation.clickable
import androidx.compose.foundation.combinedClickable
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.ColumnScope
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.heightIn
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.requiredWidth
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.LazyListScope
import androidx.compose.foundation.lazy.itemsIndexed
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.AlertDialog
import androidx.compose.material3.HorizontalDivider
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Surface
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.runtime.Composable
import androidx.compose.runtime.State
import androidx.compose.runtime.derivedStateOf
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.platform.LocalConfiguration
import androidx.compose.ui.platform.LocalDensity
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.rememberTextMeasurer
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.IntOffset
import androidx.compose.ui.unit.IntRect
import androidx.compose.ui.unit.IntSize
import androidx.compose.ui.unit.LayoutDirection
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.compose.ui.window.Popup
import androidx.compose.ui.window.PopupPositionProvider
import androidx.compose.ui.window.PopupProperties
import com.hhst.youtubelite.R
import com.hhst.youtubelite.ui.theme.SettingsTokens
import com.hhst.youtubelite.extractor.Chapter
import com.hhst.youtubelite.extractor.VideoId
import com.hhst.youtubelite.player.PlayerUiState
import com.hhst.youtubelite.player.sponsor.SponsorBlockManager
import com.hhst.youtubelite.ui.YoutubeThumb

/** What a Subtitles dropdown pick means. */
private sealed interface SubtitlePick {
    data class Language(val key: String) : SubtitlePick
    data object Style : SubtitlePick
}

@Composable
fun PlayerAnchorDropdown(
    menu: PlayerAnchorMenu?,
    state: PlayerUiState,
    positionState: State<Long>,
    callbacks: PlayerSurfaceCallbacks,
    onDismiss: () -> Unit,
    onSubtitleStyle: () -> Unit = {},
) {
    when (menu) {
        PlayerAnchorMenu.Speed -> OptionDropdown(
            rows = PlayerUi.SpeedChoices.map { OptionRow(it, PlayerUi.speedLabel(it)) },
            selected = state.speed,
            onPick = { speed ->
                speed?.let(callbacks::onSpeed)
                onDismiss()
            },
            onDismiss = onDismiss,
        )
        PlayerAnchorMenu.Quality -> OptionDropdown(
            rows = buildList<OptionRow<String>> {
                add(OptionRow(null, stringResource(R.string.player_quality_auto)))
                state.qualities.forEach { add(OptionRow(it, it)) }
            },
            selected = state.qualityLabel,
            onPick = { callbacks.onQuality(it); onDismiss() },
            onDismiss = onDismiss,
        )
        PlayerAnchorMenu.Subtitles -> {
            // Languages only — no "off" row. Tapping the active language
            // turns captions off. Style sits under the list.
            OptionDropdown(
                rows = if (state.subtitleTracks.isEmpty()) {
                    listOf(OptionRow(null, stringResource(R.string.no_subtitles), enabled = false))
                } else {
                    state.subtitleTracks.map { track ->
                        val lang = PlayerUi.languageLabel(track.language)
                        val label = if (track.autoGenerated) {
                            "$lang ${stringResource(R.string.subtitle_auto_generated)}"
                        } else {
                            lang
                        }
                        OptionRow(SubtitlePick.Language(track.key), label)
                    }
                },
                selected = if (state.subtitleEnabled) {
                    state.subtitleKey?.let { SubtitlePick.Language(it) }
                } else {
                    null
                },
                onPick = { pick ->
                    when (pick) {
                        is SubtitlePick.Language -> callbacks.onSubtitle(pick.key)
                        SubtitlePick.Style -> onSubtitleStyle()
                        null -> Unit
                    }
                    onDismiss()
                },
                onDismiss = onDismiss,
                footer = OptionRow(SubtitlePick.Style, stringResource(R.string.subtitle_style)),
            )
        }
        PlayerAnchorMenu.Segments -> {
            val jumpedTemplate = stringResource(R.string.jumped_to_segment)
            SegmentsDropdown(
                chapters = state.chapters,
                segments = state.sponsorSegments,
                positionState = positionState,
                fallbackThumb = state.videoId?.let { VideoId.thumbnailUrl(it) },
                onSeek = { startMs, label ->
                    callbacks.onSeek(startMs)
                    callbacks.onHint(jumpedTemplate.format(label))
                    onDismiss()
                },
                onDismiss = onDismiss,
            )
        }
        null -> Unit
    }
}

@Composable
private fun <T> OptionDropdown(
    rows: List<OptionRow<T>>,
    selected: T?,
    onPick: (T?) -> Unit,
    onDismiss: () -> Unit,
    footer: OptionRow<T>? = null,
) {
    val menuWidth = popupMenuWidth(rows.map { it.label } + listOfNotNull(footer?.label))
    ListPopup(onDismiss = onDismiss, width = menuWidth) {
        rows.forEach { row ->
            val isSelected = row.value == selected
            Row(
                modifier = Modifier
                    .width(menuWidth)
                    .clickable(enabled = row.enabled) { onPick(row.value) }
                    .padding(horizontal = 16.dp, vertical = 10.dp),
                verticalAlignment = Alignment.CenterVertically,
            ) {
                Text(
                    text = row.label,
                    modifier = Modifier.fillMaxWidth(),
                    fontSize = SettingsTokens.BodySize.sp,
                    fontWeight = FontWeight.Normal,
                    maxLines = 1,
                    overflow = TextOverflow.Ellipsis,
                    color = when {
                        !row.enabled -> MaterialTheme.colorScheme.onSurfaceVariant.copy(alpha = 0.5f)
                        isSelected -> MaterialTheme.colorScheme.primary
                        else -> MaterialTheme.colorScheme.onSurfaceVariant
                    },
                )
            }
        }
        footer?.let { extra ->
            HorizontalDivider(color = MaterialTheme.colorScheme.outline.copy(alpha = 0.5f))
            Row(
                modifier = Modifier
                    .width(menuWidth)
                    .clickable { onPick(extra.value) }
                    .padding(horizontal = 16.dp, vertical = 10.dp),
                verticalAlignment = Alignment.CenterVertically,
            ) {
                Text(
                    text = extra.label,
                    modifier = Modifier.fillMaxWidth(),
                    fontSize = SettingsTokens.BodySize.sp,
                    maxLines = 1,
                    overflow = TextOverflow.Ellipsis,
                    color = MaterialTheme.colorScheme.onSurface,
                )
            }
        }
    }
}

@Composable
private fun SegmentsDropdown(
    chapters: List<Chapter>,
    segments: List<SponsorBlockManager.Segment>,
    positionState: State<Long>,
    fallbackThumb: String?,
    onSeek: (Long, String) -> Unit,
    onDismiss: () -> Unit,
) {
    var preview by remember { mutableStateOf<Chapter?>(null) }
    // Only the current-chapter index depends on the ticking position; read
    // it through derivedStateOf so the 4 Hz ticks recompose this menu only
    // when the highlighted chapter actually changes.
    val currentIndex by remember(chapters) {
        derivedStateOf {
            val positionMs = positionState.value
            var idx = -1
            chapters.forEachIndexed { i, ch ->
                if (positionMs >= ch.startSeconds * 1000L) idx = i
            }
            idx
        }
    }
    // Width must be measured on the same text the rows render (localized
    // category labels can be wider than the raw key).
    val labels = buildList {
        if (chapters.isNotEmpty()) {
            chapters.forEach {
                add(it.title.ifBlank { stringResource(R.string.segments) } + "  " +
                    PlayerUi.formatTime(it.startSeconds * 1000L))
            }
        } else if (segments.isNotEmpty()) {
            segments.forEach {
                add(stringResource(PlayerUi.segmentLabelRes(it.category)) + "  " +
                    PlayerUi.formatTime(it.startMs))
            }
        } else {
            add(stringResource(R.string.no_segments))
        }
    }
    val menuWidth = popupMenuWidth(labels)
    val previewChapter = preview
    if (previewChapter != null) {
        val startMs = previewChapter.startSeconds * 1000L
        val title = previewChapter.title.ifBlank { stringResource(R.string.segments) }
        SegmentPreviewDialog(
            title = title,
            timeLabel = PlayerUi.formatTime(startMs),
            thumbnailUrl = previewChapter.previewUrl ?: fallbackThumb,
            onJump = { onSeek(startMs, title) },
            onDismiss = { preview = null },
        )
        return
    }
    LazyPopup(onDismiss = onDismiss, width = menuWidth) {
        if (chapters.isNotEmpty()) {
            itemsIndexed(chapters) { index, chapter ->
                val startMs = chapter.startSeconds * 1000L
                val title = chapter.title.ifBlank { stringResource(R.string.segments) }
                val selected = index == currentIndex
                Row(
                    modifier = Modifier
                        .fillMaxWidth()
                        .combinedClickable(
                            onClick = { onSeek(startMs, title) },
                            onLongClick = { preview = chapter },
                        )
                        .padding(horizontal = 16.dp, vertical = 10.dp),
                    verticalAlignment = Alignment.CenterVertically,
                    horizontalArrangement = Arrangement.spacedBy(12.dp),
                ) {
                    Text(
                        text = title,
                        modifier = Modifier
                            .weight(1f)
                            .basicMarquee(iterations = Int.MAX_VALUE),
                        color = if (selected) {
                            MaterialTheme.colorScheme.primary
                        } else {
                            MaterialTheme.colorScheme.onSurface
                        },
                        fontSize = SettingsTokens.BodySize.sp,
                        fontWeight = FontWeight.Normal,
                        maxLines = 1,
                        overflow = TextOverflow.Clip,
                    )
                    Text(
                        PlayerUi.formatTime(startMs),
                        fontSize = SettingsTokens.DetailSize.sp,
                        color = MaterialTheme.colorScheme.onSurfaceVariant,
                        maxLines = 1,
                    )
                }
                if (index != chapters.lastIndex) {
                    HorizontalDivider(color = MaterialTheme.colorScheme.outline.copy(alpha = 0.5f))
                }
            }
        } else if (segments.isNotEmpty()) {
            itemsIndexed(segments) { index, segment ->
                val label = stringResource(PlayerUi.segmentLabelRes(segment.category))
                Row(
                    modifier = Modifier
                        .fillMaxWidth()
                        .clickable { onSeek(segment.startMs, label) }
                        .padding(horizontal = 16.dp, vertical = 10.dp),
                    verticalAlignment = Alignment.CenterVertically,
                    horizontalArrangement = Arrangement.spacedBy(12.dp),
                ) {
                    Box(
                        Modifier
                            .size(12.dp)
                            .clip(CircleShape)
                            .background(PlayerUi.segmentColor(segment.category)),
                    )
                    Text(
                        text = label,
                        modifier = Modifier
                            .weight(1f)
                            .basicMarquee(iterations = Int.MAX_VALUE),
                        color = MaterialTheme.colorScheme.onSurface,
                        fontSize = SettingsTokens.BodySize.sp,
                        maxLines = 1,
                        overflow = TextOverflow.Clip,
                    )
                    Text(
                        PlayerUi.formatTime(segment.startMs),
                        fontSize = SettingsTokens.DetailSize.sp,
                        color = MaterialTheme.colorScheme.onSurfaceVariant,
                        maxLines = 1,
                    )
                }
                if (index != segments.lastIndex) {
                    HorizontalDivider(color = MaterialTheme.colorScheme.outline.copy(alpha = 0.5f))
                }
            }
        } else {
            item {
                Text(
                    text = stringResource(R.string.no_segments),
                    modifier = Modifier
                        .fillMaxWidth()
                        .padding(horizontal = 16.dp, vertical = 10.dp),
                    color = MaterialTheme.colorScheme.onSurfaceVariant,
                    fontSize = SettingsTokens.BodySize.sp,
                    maxLines = 1,
                )
            }
        }
    }
}

@Composable
private fun SegmentPreviewDialog(
    title: String,
    timeLabel: String,
    thumbnailUrl: String?,
    onJump: () -> Unit,
    onDismiss: () -> Unit,
) {
    AlertDialog(
        onDismissRequest = onDismiss,
        containerColor = MaterialTheme.colorScheme.surface,
        text = {
            Column {
                YoutubeThumb(
                    url = thumbnailUrl,
                    modifier = Modifier
                        .fillMaxWidth()
                        .height(160.dp)
                        .clip(RoundedCornerShape(8.dp)),
                    contentDescription = stringResource(R.string.thumbnail),
                )
                Text(
                    text = title,
                    modifier = Modifier.padding(top = 12.dp),
                    color = MaterialTheme.colorScheme.onSurface,
                    fontSize = SettingsTokens.TitleSize.sp,
                    fontWeight = FontWeight.Bold,
                )
                Text(
                    text = timeLabel,
                    modifier = Modifier.padding(top = 4.dp),
                    color = MaterialTheme.colorScheme.onSurfaceVariant,
                    fontSize = SettingsTokens.BodySize.sp,
                )
            }
        },
        confirmButton = {
            TextButton(onClick = onJump) {
                Text(stringResource(R.string.jump), color = MaterialTheme.colorScheme.primary)
            }
        },
        dismissButton = {
            TextButton(onClick = onDismiss) {
                Text(stringResource(R.string.close), color = MaterialTheme.colorScheme.onSurfaceVariant)
            }
        },
    )
}

/** Measured label widths, memoized across menus (bounded LRU) so reopening a
 *  menu — or a 4 Hz recomposition while one is open — never re-measures text
 *  on the main thread. */
/** Below this count every label is measured; above it, only the longest few. */
private const val MEASURE_SAMPLE_CAP = 48

/** How many longest-by-character-count labels are measured for huge lists. */
private const val MEASURE_SAMPLE = 24

private val labelWidthCache = object : LinkedHashMap<String, Int>(64, 0.75f, true) {
    override fun removeEldestEntry(eldest: MutableMap.MutableEntry<String, Int>): Boolean =
        size > 128
}

@Composable
private fun popupMenuWidth(labels: List<String>): Dp {
    val density = LocalDensity.current
    val screenPx = with(density) { LocalConfiguration.current.screenWidthDp.dp.toPx() }
    // 16 dp horizontal padding × 2, plus slack so measurement cannot undershoot.
    val padPx = with(density) { 40.dp.toPx() }
    val measurer = rememberTextMeasurer()
    val style = TextStyle(fontSize = SettingsTokens.BodySize.sp, fontWeight = FontWeight.Normal)
    val contentPx = remember(labels) {
        // Measuring every label janks first paint on videos with 100+
        // chapters. Within one text style, character count is a safe proxy
        // for rendered width, so for huge lists only the longest few labels
        // need real measurement — the max over that sample bounds the menu
        // width with the same practical result.
        val candidates = if (labels.size <= MEASURE_SAMPLE_CAP) {
            labels
        } else {
            labels.sortedByDescending { it.length }.take(MEASURE_SAMPLE)
        }
        candidates.maxOfOrNull { label ->
            labelWidthCache.getOrPut(label) {
                measurer.measure(text = label, style = style, maxLines = 1).size.width
            }
        } ?: 0
    }
    val menuPx = MiniPlayerLayout.popupWidthPx(contentPx + padPx.toInt(), screenPx.toInt())
    return with(density) { menuPx.toDp() }
}

/** Small menu popup for short lists (few rows, already measured). */
@Composable
private fun ListPopup(
    onDismiss: () -> Unit,
    width: Dp,
    content: @Composable ColumnScope.() -> Unit,
) {
    val maxHeight = (LocalConfiguration.current.screenHeightDp * 0.7f).dp
    Popup(
        popupPositionProvider = BelowAnchorPositionProvider,
        onDismissRequest = onDismiss,
        properties = PopupProperties(
            focusable = true,
            clippingEnabled = false,
        ),
    ) {
        Surface(
            modifier = Modifier.requiredWidth(width),
            shape = RoundedCornerShape(4.dp),
            color = MaterialTheme.colorScheme.surface,
            tonalElevation = 0.dp,
            shadowElevation = 8.dp,
        ) {
            Column(
                modifier = Modifier
                    .fillMaxWidth()
                    .heightIn(max = maxHeight)
                    .verticalScroll(rememberScrollState()),
                content = content,
            )
        }
    }
}

/** [ListPopup] for long lists (chapters): lazy rows under the same 70% cap. */
@Composable
private fun LazyPopup(
    onDismiss: () -> Unit,
    width: Dp,
    content: LazyListScope.() -> Unit,
) {
    val maxHeight = (LocalConfiguration.current.screenHeightDp * 0.7f).dp
    Popup(
        popupPositionProvider = BelowAnchorPositionProvider,
        onDismissRequest = onDismiss,
        properties = PopupProperties(
            focusable = true,
            clippingEnabled = false,
        ),
    ) {
        Surface(
            modifier = Modifier.requiredWidth(width),
            shape = RoundedCornerShape(4.dp),
            color = MaterialTheme.colorScheme.surface,
            tonalElevation = 0.dp,
            shadowElevation = 8.dp,
        ) {
            LazyColumn(
                modifier = Modifier
                    .fillMaxWidth()
                    .heightIn(max = maxHeight),
                content = content,
            )
        }
    }
}

/** Place the popup under the parent, or above it when the bottom would clip. */
private object BelowAnchorPositionProvider : PopupPositionProvider {
    override fun calculatePosition(
        anchorBounds: IntRect,
        windowSize: IntSize,
        layoutDirection: LayoutDirection,
        popupContentSize: IntSize,
    ): IntOffset {
        val maxX = (windowSize.width - popupContentSize.width).coerceAtLeast(0)
        val x = if (layoutDirection == LayoutDirection.Ltr) {
            anchorBounds.left.coerceIn(0, maxX)
        } else {
            (anchorBounds.right - popupContentSize.width).coerceIn(0, maxX)
        }
        val y = if (anchorBounds.bottom + popupContentSize.height <= windowSize.height) {
            anchorBounds.bottom
        } else {
            (anchorBounds.top - popupContentSize.height).coerceAtLeast(0)
        }
        return IntOffset(x, y)
    }
}
